### PR TITLE
Fix confusing weakref constructor overload

### LINKED ISSUE #2536: [BUG] Confusing weakref constructor copy the object instead of creating a weakref
My colleague and I stumbled on a very confusing part of the API. When calling pybind11::weakref with a single argument that is of type py::object as such:
```

py::object WRONGcreateWeakRef(py::object object)
{
        return py::weakref(object);
}

```
Here is a correct way to call it:

```
py::object GOODcreateWeakRef(py::object object)
{
        return py::weakref(static_cast<py::handle>(object));
}
```

This is caused by the fact that the weakref constructor is explicit and the copy constructor is called instead. The result is that no weakref is created. This is very confusing. The copy constructor should allow only to copy weakref. May be by using a private copy constructor that takes an object and an public copy constructor that takes a weakref.

After some discussion on gitter, it seems that https://github.com/pybind/pybind11/pull/2349 will solve this issue by raising a TypeError. However, the API would be still awkward.

### PR DESCRIPTION
**Pull request by YannickJadoul**
## Description

Fixes #2536, where the two `weakref` constructors from `handle` and `object` do different things.
Demonstrated by failing tests in the first commit, fixed in the second one.

## Suggested changelog entry:

```rst
Fix the ``weakref`` constructor from ``py::object`` to create a new ``weakref`` on conversion.
```

### CODE REVIEW

File: include/pybind11/pytypes.h [hunk 1]
```diff
@@ -1163,11 +1163,16 @@ class float_ : public object {
 
 class weakref : public object {
 public:
-    PYBIND11_OBJECT_DEFAULT(weakref, object, PyWeakref_Check)
+    PYBIND11_OBJECT_CVT(weakref, object, PyWeakref_Check, raw_weakref)
```
Comment (bstaletic) [inline include/pybind11/pytypes.h:1166]: Technically an API break. Do we care about users digging up `py::weakref::weakref()`?

File: tests/test_pytypes.py [hunk 2]
```diff
@@ -488,3 +488,45 @@ def test_builtin_functions():
...
+
+    # Apparently, you cannot weakly reference an object()
+    class WeaklyReferenced(object):
+        pass
+
+    called = [0]
+
+    def callback(wr):
+        # No `nonlocal` in Python 2
+        called[0] += 1
```
Comment (bstaletic) [inline tests/test_pytypes.py:504]: Why not just use `global`?

File: tests/test_pytypes.py [hunk 3]
```diff
@@ -488,3 +488,45 @@ def test_builtin_functions():
...
+
+    obj = WeaklyReferenced()
+    assert getweakrefcount(obj) == 0
+    wr = m.weakref_from_handle(obj)  # noqa: F841
+    assert getweakrefcount(obj) == 1
+
+    obj = WeaklyReferenced()
+    assert getweakrefcount(obj) == 0
+    wr = m.weakref_from_handle_and_function(obj, callback)  # noqa: F841
```
Comment (bstaletic) [inline tests/test_pytypes.py:513]: Can't you just not assign the weak reference?

File: tests/test_pytypes.py (hunk 2 above)
Comment (YannickJadoul) [reply tests/test_pytypes.py:504]: Because it's not `global`? It's `nonlocal`, I think (?), but that's not available in Python 2?

File: tests/test_pytypes.py (hunk 3 above)
Comment (YannickJadoul) [reply tests/test_pytypes.py:513]: Well, it will be gone. Will the destructor still be called then? I don't think so. I think I/we want to check this callback being called on `del obj`, no?

File: include/pybind11/pytypes.h (hunk 1 above)
Comment (YannickJadoul) [reply include/pybind11/pytypes.h:1166]: @bstaletic and I discussed this privately, btw.

I don't think `weakref()` is that useful: it's constructing a `weakref` object with a `(PyObject *) NULL` inside. pybind11 is reasonably inconsistent about which types allow this and which ones don't. I'd say it's probably a discussion for another time on the sense/nonsense of default constructor of `object`-subclasses.

I could add either `PYBIND11_OBJECT_CVT_DEFAULT` or just add a single line `weakref() = default;` here, though?

File: tests/test_pytypes.py (hunk 2 above)
Comment (bstaletic) [reply tests/test_pytypes.py:504]: I thought `global` meant "first" variable of `name` going from the global scope towards the current scope. Carry on.

File: tests/test_pytypes.py (hunk 3 above)
Comment (YannickJadoul) [reply tests/test_pytypes.py:513]: This is in the interactive repl, though?

Have a look at this:

```
$ python3 - << EOF
> import weakref
> class c: pass
> o = c()
> weakref.ref(o, lambda x: print(1))
> print('bump')
> del o
> 
> EOF
bump
```
vs.
```
$ python3 - << EOF
> import weakref
> class c: pass
> o = c()
> wr = weakref.ref(o, lambda x: print(1))
> print('bump')
> del o
> EOF
bump
1
```

File: tests/test_pytypes.py (hunk 2 above)
Comment (YannickJadoul) [reply tests/test_pytypes.py:504]: I wasn't completely sure either, but this test says I'm right (beware, this is ugly!):

```
>>> def f():
...     i = 0
...     def g():
...             global i
...             i += 1
...     g()
...     g()
...     return i
... 
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in f
  File "<stdin>", line 5, in g
NameError: name 'i' is not defined
>>> i = 0
>>> f()
0
>>> i
2
```


But wait, I can still pick something better!

Comment (YannickJadoul) [reply tests/test_pytypes.py]: Better this way? It's just as weird, but looks better and slightly more descriptive.

File: include/pybind11/pytypes.h (hunk 1 above)
Comment (rwgk) [reply include/pybind11/pytypes.h:1171]: `weakref() = default;` looks good to me, maybe with a comment
```
// Provided mainly for uniformity. Constructs a weakref object with a (PyObject *) NULL inside.
weakref() = default;
```
I almost feel the `PYBIND11_OBJECT_DEFAULT` macro isn't useful ("what default?") and getting rid of it and explicitly writing out `something() = default;` is more readable code ... but that's a question for another day, maybe.

**Comment by rwgk** [comment]
Looks good to me. I'll globally test this (without the default constructor) to see if anyone is relying on it, mostly out of interest. Preserving the default constructor seems best irrespectively.

File: include/pybind11/pytypes.h (hunk 1 above)
Comment (YannickJadoul) [reply include/pybind11/pytypes.h:1171]: Agreed. This macros make things very confusing and inconsistent (some `py::object` subclasses are nullable, others aren't; some try to be safe when calling methods on them, others don't). I actually would like to doubt the validity of default constructors here in general. But maybe that's a challenge for another day.

File: tests/test_pytypes.py [hunk 4]
```diff
@@ -541,3 +541,45 @@ def test_pass_bytes_or_unicode_to_string_types():
...
+
+    # Apparently, you cannot weakly reference an object()
+    class WeaklyReferenced(object):
+        pass
+
+    def callback(wr):
+        # No `nonlocal` in Python 2
+        callback.called += 1
+
+    callback.called = 0
```
Comment (rwgk) [inline tests/test_pytypes.py:557]: Resetting `callback.called` only once makes the tests below order dependent. If someone has a reason to shuffle the test, they may get surprised. I'd move this down do just above the the `weakref_from_*_and_function` calls.

But I think I'd go one step further, using `@pytest.mark.parametrize` to reduce copy-pasting, that would automatically avoid the order dependence.

**Review by rwgk — APPROVED** [review]
Google-global testing this as-is (without the default constructor) came back green. Might be nice to add something along the lines of "very unlikely to be useful but supplied for backward compatibility" in a comment when you put back the default constructor.

**Comment by YannickJadoul** [comment]
> Might be nice to add something along the lines of "very unlikely to be useful but supplied for backward compatibility" in a comment when you put back the default constructor.

If we want to do that, I think we should go with an official deprecation, but I'm fine just being fully backward compatible and pushing the "let's make all `py::object` subclasses consistent" into the future.

File: tests/test_pytypes.py (hunk 4 above)
Comment (YannickJadoul) [reply tests/test_pytypes.py]: Hmm, maybe. I tried something. I hope this is still readable enough to track down when one of the two tests fails, but it's shorter, at least.

**Comment by YannickJadoul** [comment]
> you put back the default constructor.

I added `PYBIND11_OBJECT_CVT_DEFAULT` to make clear that this is part of the whole `PYBIND11_OBJECT*` macro zoo. This groups things if we ever were to e.g. deprecate the default contructors of `py::object` subclasses, in some hypothetical future.

**Review by bstaletic — APPROVED** [review]

**Comment by YannickJadoul** [comment]
I think we went over all bits and pieces, then :-) Let's close another PR and issue.

Thanks, all!
