### PR TITLE
fix: throwing repr caused a segfault

### LINKED ISSUE #2383: Segfault when __repr__ throws
## Issue description

If a `__repr__` throws, then passing an invalid object causes a segfault.

## Reproducible example code

```diff
diff --git a/tests/test_exceptions.cpp b/tests/test_exceptions.cpp
index 372d0ae..8244322 100644
--- a/tests/test_exceptions.cpp
+++ b/tests/test_exceptions.cpp
@@ -218,4 +218,7 @@ TEST_SUBMODULE(exceptions, m) {
         }
     });

+    // Test repr that cannot be displayed
+    m.def("simple_bool_passthrough", [](bool x){return x;});
+
 }
diff --git a/tests/test_exceptions.py b/tests/test_exceptions.py
index b794e3d..64bdc63 100644
--- a/tests/test_exceptions.py
+++ b/tests/test_exceptions.py
@@ -179,3 +179,14 @@ def test_nested_throws(capture):
     with pytest.raises(m.MyException5) as excinfo:
         m.try_catch(m.MyException, pycatch, m.MyException, m.throws5)
     assert str(excinfo.value) == "this is a helper-defined translated exception"
+
+
+# This can often happen if you wrap a pybind11 class in a Python wrapper
+def test_invalid_repr():
+
+    class MyRepr(object):
+        def __repr__(self):
+            raise AttributeError("Example error")
+
+
+    m.simple_bool_passthrough(MyRepr())
```

### PR DESCRIPTION
**Pull request by henryiii**
Closes #2383 , thanks to hint from @jbarlow83 .

### CODE REVIEW

File: include/pybind11/pybind11.h [hunk 1]
```diff
@@ -776,7 +776,11 @@ class cpp_function : public function {
             for (size_t ti = overloads->is_constructor ? 1 : 0; ti < args_.size(); ++ti) {
                 if (!some_args) some_args = true;
                 else msg += ", ";
-                msg += pybind11::repr(args_[ti]);
+                try {
+                    msg += pybind11::repr(args_[ti]);
+                } catch (const error_already_set&) {
+                    msg += pybind11::repr(args_[ti].get_type());
```
Comment (henryiii) [inline include/pybind11/pybind11.h:782]: The repr produced is pretty ugly, but better than a segfault. Maybe should indicate it's an instance of the class?

```
>       m.simple_bool_passthrough(MyRepr())
E       TypeError: simple_bool_passthrough(): incompatible function arguments. The following argument types are supported:
E           1. (arg0: bool) -> bool
E
E       Invoked with: <class 'test_exceptions.test_invalid_repr.<locals>.MyRepr'>

test_exceptions.py:162: TypeError
```

Comment (jbarlow83) [reply include/pybind11/pybind11.h:782]: Yes, it should probably say it's an instance.

This is the sort of situation where Python would chain exceptions ("While handling this error, another error occurred..."). but there's no C API for that. Although I wonder if it's worth indicating that an exception occurred in `repr()`.

**Comment by jbarlow83** [comment]
The call to `pybind11::str` at line 795 can probably trigger a segfault too, if `__str__` raise as an error.

File: include/pybind11/pybind11.h (hunk 1 above)
Comment (henryiii) [reply include/pybind11/pybind11.h:782]: It doesn't seem like this information is always available - some compilers are not showing it. Maybe just a "<repr raised error>" message would work?

Comment (jbarlow83) [reply include/pybind11/pybind11.h:782]: Maybe `discard_as_unraisable()` does make sense here. It would get the stack trace and exception from `__repr__` out, and would not be compiler-dependent.

Comment (henryiii) [reply include/pybind11/pybind11.h]: Okay, we could use it then; I've added an unchanging  `<repr raised Error>` currently but would be happy to change it.

Comment (YannickJadoul) [reply include/pybind11/pybind11.h]: We could potentially put the exception as string into `<repr raised str(exc)>`, but maybe we'll start some infinite recursion, then?

Comment (virtuald) [reply include/pybind11/pybind11.h]: There is a C API for chaining exceptions, see #2112

Comment (jbarlow83) [reply include/pybind11/pybind11.h]: What I meant was, for their own reasons, the Python core developers chose to not automate chaining exceptions in C or provide an API to make it easier to do.
https://www.python.org/dev/peps/pep-0490/
It's hard to tell what to make of the situation, in terms of what they think C extensions to do.

We potentially have exceptions for each argument to the function, and each of those could involve an individual chain of exceptions - potentially there's a tree of exceptions. I think chaining these exceptions to each other could muddy the waters because it could end up linking the exceptions from attempts to repr() different arguments. Write unraisable here gets the exception out, and then we print a message complaining that we can't repr() the arguments.

**Comment by henryiii** [comment]
I currently just have a simple `<repr raised Error>`, should we do more? It's still better than a segfault. ;)

**Comment by YannickJadoul** [comment]
Nah, that's probably fine enough. If this happens, it's because there's a mistake anyway, right? We just don't want stuff to segfault.

**Comment by YannickJadoul** [comment]
Is this related to #1716, though?

**Comment by henryiii** [comment]
I think it would solve that segfault, but the error message would not be as ideal, I'd think?

**Comment by YannickJadoul** [comment]
> I think it would solve that segfault, but the error message would not be as ideal, I'd think?

Reading again, it might not be solved, actually? It seems like `type_caster` for `bool` leaves the error indicator set in #1716?

**Comment by wjakob** [comment]
nice, I vaguely remember running into this in a project of mine, but I never got around to fixing it.

**Comment by henryiii** [comment]
I think this can go in, then, and the messaging can be improved later if it's needed?
