### PR TITLE
Fix py::make_iterator's __next__() for past-the-end calls

### LINKED ISSUE #896: Attempting to iterate over python iterable, in c++, iterates past the end with bound c++ types.
### Issue
Attempting to iterate over python iterable, in c++, iterates past the end with bound c++ types. It seems that comparing the end iterator to the sentinel attempts to advance the end iterator past the end. When iterating a python type calling PyIter_Next past the end simply returns NULL however for a bound STL container this invokes undefined behaviour.

Occurs on:
Windows 10 (VS 2017), Ubuntu 17.04 (gcc 7.0)
pybind11 2.1.1 and master ( 0365d49 )

### Example
cpp:
```cpp
#include <pybind11/pybind11.h>
#include <pybind11/stl_bind.h>

namespace py = pybind11;

PYBIND11_MAKE_OPAQUE(std::vector<int>)

PYBIND11_MODULE(IterableTest, m)
{
    py::bind_vector<std::vector<int>>(m, "VectorInt");

    m.def("iter_test", [] (py::iterable iterable)
    {
        auto iter = py::iter(iterable);
        while (iter != py::iterator::sentinel())
        {
            py::print("got value: ", *iter);
            ++iter;
        }
    });
}
```
python:
```python
from IterableTest import *

ivec = VectorInt()
ivec.append(3)
ivec.append(2)
ivec.append(1)

iter_test(ivec)
```
example output:
```
got value:  3
got value:  2
got value:  1
*debug assert iterator is not incrementable*
```

### PR DESCRIPTION
**Pull request by dean0x7d**
Fixes #896.

From Python docs: Once an iterator’s `__next__()` method raises `StopIteration`, it must continue to do so on subsequent calls. Implementations that do not obey this property are deemed broken.

### CODE REVIEW

File: include/pybind11/pybind11.h [hunk 1]
```diff
@@ -1378,8 +1378,10 @@ iterator make_iterator(Iterator first, Sentinel last, Extra &&... extra) {
                     ++s.it;
                 else
                     s.first = false;
-                if (s.it == s.end)
+                if (s.it == s.end) {
+                    s.first = true;
```
Comment (jagerman) [inline include/pybind11/pybind11.h]: It was a bit non-obvious to me at first glance why this works, which I think may have been due to the `first` name; a rename of `first` to something like `first_or_done` would be more self-documenting.

**Comment by jagerman** [comment]
LGTM, with one minor comment about the variable name being slightly confusing.

File: include/pybind11/pybind11.h (hunk 1 above)
Comment (dean0x7d) [inline include/pybind11/pybind11.h]: Good point. Renamed.
