### PR TITLE
Workaround NVCC parse failure in `cast_op`

### LINKED ISSUE #4606: [BUG]: Cuda 12.1: error: expected template-name before ‘<’ token
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.4

### Problem description

```
/usr/include/pybind11/detail/../cast.h: In function ‘typename pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type
>::cast_op_type<T> pybind11::detail::cast_op(make_caster<T>&)’:
/usr/include/pybind11/detail/../cast.h:45:120: error: expected template-name before ‘<’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                        ^
/usr/include/pybind11/detail/../cast.h:45:120: error: expected identifier before ‘<’ token
/usr/include/pybind11/detail/../cast.h:45:123: error: expected primary-expression before ‘>’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                           ^
/usr/include/pybind11/detail/../cast.h:45:126: error: expected primary-expression before ‘)’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                              ^
```

### Reproducible example code

```text
echo "#include <pybind11/functional.h>" >> t.cu
nvcc -isystem=/usr/include/python3.10 -c t.cu
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by Flamefire**
There is a bug in some CUDA versions (observed in CUDA 12.1 and 11.7 w/ GCC 12.2), that makes `cast_op` fail to compile:
  `cast.h:45:120: error: expected template-name before ‘<’ token`

Defining the nested type as an alias and using it allows this to work without any change in semantics.

Fixes #4606

The alternative using a `static_cast` or similar fails due to ambiguity with the `const Foo&` and `Foo&` operators (one of the tests)

## Suggested changelog entry:

```rst
Improve compatibility with the nvcc compiler (especially CUDA 12.1/12.2)

```

### CODE REVIEW

File: include/pybind11/cast.h [hunk 1]
```diff
@@ -42,13 +42,15 @@ using make_caster = type_caster<intrinsic_t<type>>;
 // Shortcut for calling a caster's `cast_op_type` cast operator for casting a type_caster to a T
 template <typename T>
 typename make_caster<T>::template cast_op_type<T> cast_op(make_caster<T> &caster) {
-    return caster.operator typename make_caster<T>::template cast_op_type<T>();
+    using result_t = typename make_caster<T>::template cast_op_type<T>;
```
Comment (rwgk) [inline include/pybind11/cast.h:45]: Could you please add a comment at the end of the line, e.g.

```
// See PR #4893.
```

Also below.

In case someone later is considering inlining `result_t` again, they can easily know why it's here.

**Comment by correaa** [comment]
If someone has this problem and cannot update pybind11 for any reason, note that, to me at least, this doesn't happen with GCC 11 as host compiler. e.g. `cmake .. -DCMAKE_CUDA_HOST_COMPILER=g++-11 ...`

**Comment by correaa** [comment]
not sure, how can one check if this PR went into a tagged version (not master) of pybind11 ?

**Comment by rwgk** [comment]
> not sure, how can one check if this PR went into a tagged version (not master) of pybind11 ?

There was no release of any kind in the time after this PR was merged.

**Comment by Flamefire** [comment]
> not sure, how can one check if this PR went into a tagged version (not master) of pybind11 ?

Github offers a nice way: Open the merge commit found in the PR (message like "<XYZ> merged commit [3414c56](https://github.com/pybind/pybind11/commit/3414c56b6c7c521d868c9a137ca2ace2e26b5b2e) into pybind:master") and Github will show the branches and tags this is contained in between the commit message and author(s). Right now it only shows the master branch but once a tag is out, that would be shown too unless the tag is from a different branch.

In the meantime you can pick this PR as a patch and apply it manully by appending `.diff` or `.patch` to the commit or PR URL, e.g. https://github.com/pybind/pybind11/pull/4893.patch
