### PR TITLE
fix(regression): support embedded submodule

### LINKED ISSUE #5649: [BUG]: cannot register submodules for embedded modules
### Required prerequisites

- [x] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

c125cc789ca1be95bcd10479c568d5d260c743ad

### Problem description

Pybinds `module_::def_submodule` function requires the module to have a `__file__` attribute. However, when creating an embedded module this attribute is not set. As a workaround, I am currently setting the attribute manually:

```c++
PYBIND11_EMBEDDED_MODULE(x, m) {
    m.attr("__file__") = "<embedded>";
    m.def_submodule("y");
}
```

I would think that adding submodules is a valid use-case that should not need such workarounds.

### Reproducible example code

```text

```

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by henryiii**
## Description

Fix #5649.

## Suggested changelog entry:

```rst
* Fix a regression in #5584.
```

### CODE REVIEW

File: include/pybind11/pybind11.h [hunk 1]
```diff
@@ -1342,14 +1342,21 @@ class module_ : public object {
...
+        }
+        else if (PyErr_ExceptionMatches(PyExc_SystemError) != 0) {
+            PyErr_Clear();
+        }
+        else {
             throw error_already_set();
         }
-        result.attr("__file__") = this_file;
-#endif
+#end
```
Comment (rkaminsk) [inline include/pybind11/pybind11.h]: It has to be #endif

Comment (rkaminsk) [inline include/pybind11/pybind11.h]:
```suggestion
#endif
```

Comment (henryiii) [reply include/pybind11/pybind11.h]: Thanks!

File: include/pybind11/pybind11.h [hunk 2]
```diff
@@ -1342,13 +1342,18 @@ class module_ : public object {
...
-        result.attr("__file__") = this_module.attr("__file__");
+        if (hasattr(this_module, "__file__")) {
+            result.attr("__file__") = this_module.attr("__file__");
+        }
 #else
         handle this_file = PyModule_GetFilenameObject(m_ptr);
-        if (!this_file) {
+        if (this_file) {
+            result.attr("__file__") = this_file;
+        } else if (PyErr_ExceptionMatches(PyExc_SystemError) != 0) {
```
Comment (rwgk) [inline include/pybind11/pybind11.h:1352]: Ugh ... if we have to catch a `SystemError` here to accommodate submodules, I regret posting [this comment on PR #5584](https://github.com/pybind/pybind11/pull/5584/files#r2017618042).

I think it'll be best to get rid of this `#else` branch then.

Comment (henryiii) [reply include/pybind11/pybind11.h:1352]: It should be extremely rare, this is only for embedded submodules, normally it works. I think it's probably fine to leave this way.

Comment (rwgk) [reply include/pybind11/pybind11.h:1352]: Up to you, I'm OK if you want to keep it.

What still makes me feel uneasy: the risk of masking unexpected `SystemError`s.

Which is of course extremely low, but not zero. (Google experience: anything that can happen, does happen.)

Comment (rkaminsk) [reply include/pybind11/pybind11.h:1352]: The function is part of the Stable API and just accesses a dictionary. My two cents: the current implementation is safe.

Comment (rwgk) [reply include/pybind11/pybind11.h:1352]: Do you have a link to the implementation handy?

What's on my mind: Why does it raise `SystemError`, and not `AttributeError`?

I'd feel more cozy ignoring an `AttributeError`.

But as I said, I'm fine with this.

**Comment by rkaminsk** [comment]
The function explicitly sets the system error. I could not see any system errors in the source of the dictionary.

- https://github.com/python/cpython/blob/7dddb4e667b5eb76cbe11755051ec139b0f437a9/Objects/moduleobject.c#L644
- https://github.com/python/cpython/blob/7dddb4e667b5eb76cbe11755051ec139b0f437a9/Objects/dictobject.c#L2392

File: include/pybind11/pybind11.h (hunk 2 above)
Comment (rkaminsk) [reply include/pybind11/pybind11.h:1352]: The function explicitly sets the system error. I could not see any system errors in the source of the dictionary.

- https://github.com/python/cpython/blob/7dddb4e667b5eb76cbe11755051ec139b0f437a9/Objects/moduleobject.c#L644
- https://github.com/python/cpython/blob/7dddb4e667b5eb76cbe11755051ec139b0f437a9/Objects/dictobject.c#L2392

Comment (rwgk) [reply include/pybind11/pybind11.h:1352]: Thanks!

> The function explicitly sets the system error.

Seems like an unfortunate choice, to have it in the same class of exceptions as e.g. out-of-memory, but 🤷

Comment (henryiii) [reply include/pybind11/pybind11.h:1352]:
```
>>> SystemError.__mro__
(<class 'SystemError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>)
>>> MemoryError.__mro__
(<class 'MemoryError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>)
```

https://docs.python.org/3/library/exceptions.html#SystemError

> Raised when the interpreter finds an internal error, but the situation does not look so serious to cause it to abandon all hope.

Doesn’t seem too bad, I think it’s for things like this, exceptions that shouldn’t make it up to the user.

File: include/pybind11/pybind11.h [hunk 3]
```diff
@@ -1342,13 +1342,18 @@ class module_ : public object {
         // GraalPy doesn't support PyModule_GetFilenameObject,
         // so getting by attribute (see PR #5584)
         handle this_module = m_ptr;
-        result.attr("__file__") = this_module.attr("__file__");
+        if (hasattr(this_module, "__file__")) {
+            result.attr("__file__") = this_module.attr("__file__");
```
Comment (rwgk) [inline include/pybind11/pybind11.h:1346]: A couple years ago I took a close look at the `PyObject_HasAttr` implementation: it's actually doing a full `PyObject_GetAttr`, only to discard the attribute at the end. Suggestion to avoid two passes:

```diff
diff --git a/include/pybind11/pybind11.h b/include/pybind11/pybind11.h
index 2d74f78f..1d2cd30a 100644
--- a/include/pybind11/pybind11.h
+++ b/include/pybind11/pybind11.h
@@ -1342,8 +1342,8 @@ public:
         // GraalPy doesn't support PyModule_GetFilenameObject,
         // so getting by attribute (see PR #5584)
         handle this_module = m_ptr;
-        if (hasattr(this_module, "__file__")) {
-            result.attr("__file__") = this_module.attr("__file__");
+        if (object this_file = getattr(this_module, "__file__", py::none())) {
+            result.attr("__file__") = this_file;
         }
 #else
         handle this_file = PyModule_GetFilenameObject(m_ptr);
```

**Review by rwgk — APPROVED** [review]
A small suggestion.

File: include/pybind11/pybind11.h (hunk 3 above)
Comment (henryiii) [reply include/pybind11/pybind11.h:1346]: Interesting, yes, https://github.com/python/cpython/blob/4f2f780d534962261dcc7813e50d0dcb413a1d3c/Objects/object.c#L1417

Comment (henryiii) [reply include/pybind11/pybind11.h:1346]:
```suggestion
        if (object this_file = getattr(this_module, "__file__", py::none())) {
            result.attr("__file__") = this_file;
```
