### PR TITLE
Fix race condition with py::make_key_iterator in free threading

### LINKED ISSUE #5970: [BUG]: `make_key_iterator` type creation does not appear to be thread-safe
### Required prerequisites

- [x] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

3.0.1

### Problem description

`make_key_iterator` does not appear to be thread safe. It looks like it creates the iterator type in a way that is not safe and therefore when multiple threads call `set(iterable)` there is a race to create the iterator.
Reproducer https://github.com/ikrommyd/pybind11_iterator_race
Just run it via
```shell
uv venv -p 3.14t
source .venv/bin/activate
uv pip install .
pytest --parallel-threads=6 tests
```
and it should get you to:
```
    def test_iterator():
        c = Container()
>       assert set(c) == {"key1", "key2", "key3"}
               ^^^^^^
E       TypeError: Object of type 'iterator' is not an instance of 'iterator'
```
or another error but this is the most common one I get.
This workaround to force the iterator type to be created at module load fixes the problem:
```diff
diff --git a/src/module.cpp b/src/module.cpp
index f00f7b1..43cc8fb 100644
--- a/src/module.cpp
+++ b/src/module.cpp
@@ -29,4 +29,11 @@ PYBIND11_MODULE(_iterator_race, m, py::mod_gil_not_used()) {
         .def("__iter__", [](const Container &c) {
             return py::make_key_iterator(c.begin(), c.end());
         }, py::keep_alive<0, 1>());
+
+    // Workaround: force iterator type creation at module load (single-threaded)
+    {
+        Container dummy;
+        auto it = py::make_key_iterator(dummy.begin(), dummy.end());
+        (void)it;
+    }
 }
```

### Reproducible example code
It's best to use the repo https://github.com/ikrommyd/pybind11_iterator_race but here is the C++ module part of the reproducer.
```c++
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// Minimal class with a map that we want to iterate over
class Container {
public:
    Container() {
        data_["key1"] = 1;
        data_["key2"] = 2;
        data_["key3"] = 3;
    }

    auto begin() const { return data_.cbegin(); }
    auto end() const { return data_.cend(); }
    size_t size() const { return data_.size(); }

private:
    std::map<std::string, int> data_;
};

PYBIND11_MODULE(_iterator_race, m, py::mod_gil_not_used()) {
    m.doc() = "Minimal reproducer for pybind11 iterator race condition";

    py::class_<Container>(m, "Container")
        .def(py::init<>())
        .def("__len__", &Container::size)
        .def("__iter__", [](const Container &c) {
            return py::make_key_iterator(c.begin(), c.end());
        }, py::keep_alive<0, 1>());
}
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by colesbury**
## Description

The creation of the iterator class needs to be synchronized.

Fixes #5970

## Suggested changelog entry:

* Fix race condition in `py::make_key_iterator` with free threaded Python

### CODE REVIEW

File: include/pybind11/detail/internals.h [hunk 1]
```diff
@@ -271,7 +297,7 @@ class loader_life_support;
 /// `PYBIND11_INTERNALS_VERSION` must be incremented.
 struct internals {
 #ifdef Py_GIL_DISABLED
-    pymutex mutex;
+    pyrecursive_mutex mutex;
```
Comment (colesbury) [inline include/pybind11/detail/internals.h]: @henryiii @rwgk - I could use some advice here. I probably should have used some sort of recursive mutex here from the start -- it's pretty difficult to do the locking for `make_iterator_impl` without it.

I think changing this would require bumping `PYBIND11_INTERNALS_VERSION`, at least for `Py_GIL_DISABLED` builds. Is that acceptable?

Alternatively, maybe we should use something like [`Py_BEGIN_CRITICAL_SECTION_MUTEX`](https://docs.python.org/3/c-api/init.html#c.Py_BEGIN_CRITICAL_SECTION_MUTEX), which supports recursion and eliminates some potential lock ordering deadlocks if you call into Python. The downside is that it is 3.14+ only.

Comment (rwgk) [reply include/pybind11/detail/internals.h]: > I think changing this would require bumping `PYBIND11_INTERNALS_VERSION`, at least for `Py_GIL_DISABLED` builds. Is that acceptable?

After the v3.0.2 release, yes. We already have three other PRs that need an internals version bump.

I was planning to release today (PR #5969), but there was a show stopper. We're waiting for a fix for the segfault.

My thinking: the race isn't new, therefore it would seem reasonable to defer fixing it until after the v3.0.2 release, when we have a window of opportunity to bump the internals version.

Caveat: I don't have enough background to decide between the internals version bump and the critical section alternative.

**Comment by ikrommyd** [comment]
Thanks for working on this so quickly! I can try it with the full library that I discovered the issue with once it is in a ready-to-review state 😃

File: include/pybind11/detail/internals.h (hunk 1 above)
Comment (henryiii) [reply include/pybind11/detail/internals.h]: `Py_BEGIN_CRITICAL_SECTION_MUTEX` sounds fine, I'd be okay to deprecate and remove Python 3.13t support. Maybe we could just fix this bug on 3.14t, and then drop 3.13t in 3.1?

We are thinking about dropping 3.13t in cibuildwheel too.

Comment (henryiii) [reply include/pybind11/detail/internals.h]: Also fine to make the lock recursive in 3.1, we have several ABI bumps coming up.

Comment (colesbury) [reply include/pybind11/detail/internals.h]: Great, I think dropping 3.13t makes sense. I switched to `PyCriticalSection_BeginMutex`.

I saw there's also a py::scoped_critical_section. Not sure if you'd want to combine them.

**Comment by colesbury** [comment]
@ikrommyd - if you can run test with the full library, that would be great.

**Comment by ikrommyd** [comment]
Looks good from my side! (if I checkout `pybind11` master branch, `tests/test_core.py` fails with the original error reported in the issue `TypeError: Object of type 'iterator' is not an instance of 'iterator'`) 
image
image

**Comment by henryiii** [comment]
@rwgk what should we do with 3.13t here? Okay to drop it in a patch release, or should we gate this for 3.14t+ only (fine to leave the bug unfixed on 3.13t), and drop in the next minor release instead? CPython 3.13t was always experimental, while 3.14t is not.

**Comment by rwgk** [comment]
> Okay to drop it in a patch release

Move vote: yes, drop

I don't think 3.13t is worth the trouble doing anything special.

File: include/pybind11/detail/internals.h [hunk 2]
```diff
@@ -238,6 +239,17 @@ class pymutex {
     void unlock() { PyMutex_Unlock(&mutex); }
 };
 
+class pycritical_section {
```
Comment (rwgk) [inline include/pybind11/detail/internals.h:242]: Do we need to be careful about copy/move here?

... give me a moment to look at this with the help of some LLM ...

Comment (rwgk) [reply include/pybind11/detail/internals.h:242]: Result: be01d1ebe8ed966ef68eb05a11910f508478cf4c

(created with Cursor Composer 1 model)

**Comment by rwgk** [comment]
> @rwgk what should we do with 3.13t here? Okay to drop it in a patch release, or should we gate this for 3.14t+ only (fine to leave the bug unfixed on 3.13t), and drop in the next minor release instead? CPython 3.13t was always experimental, while 3.14t is not.

While I was at it, I went ahead and added two commits:

* 61e032eb9f8404757b698fc81feae0c4d39a8f6a
* 29840cec684546f06b5d309e7716b3a3b90962f2

I'm not sure about the second commit: @henryiii which of these jobs would you add?

**Comment by rwgk** [comment]
This job failed:

https://github.com/pybind/pybind11/actions/runs/21319724363/job/61367809291

```
Run Build Command(s): /opt/homebrew/bin/ninja -v cpptest
[0/2] /opt/homebrew/bin/cmake -P /Users/runner/work/pybind11/pybind11/build/CMakeFiles/VerifyGlobs.cmake
[0/2] cd /Users/runner/work/pybind11/pybind11/build/tests/test_with_catch && /Users/runner/work/pybind11/pybind11/build/tests/test_with_catch/test_with_catch
[ STARTING ] 2026-01-24 19:01:13.460Z
[ PYTHON   ] 3.14.2 free-threading build (v3.14.2:df793163d58, Dec  5 2025, 12:31:15) [Clang 16.0.0 (clang-1600.0.26.6)]
...
[ RUN      ] Per-Subinterpreter GIL
<frozen importlib._bootstrap>:491: RuntimeWarning: The global interpreter lock (GIL) has been enabled to load module 'widget_module', which has not declared that it can run safely without the GIL. To override this behavior and keep the GIL disabled (at your own risk), run with PYTHON_GIL=0 or -Xgil=0.
Error: The action 'C++ tests' has timed out after 3 minutes.
```

I triggered a rerun to see if it's a flake.

**Comment by rwgk** [comment]
> This job failed:
> 
> https://github.com/pybind/pybind11/actions/runs/21319724363/job/61367809291
>...
> I triggered a rerun to see if it's a flake.

It was a flake, but maybe that's a problem for another day? Or do you suspect that the changes in this PR could play a role?

**Comment by colesbury** [comment]
I'm not sure what caused that timeout, but I don't think it's related to the PR. Mixing subinterpreters and free threading isn't very well tested currently.

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -240,7 +237,7 @@ jobs:
 
 
   manylinux:
-    name: Manylinux on 🐍 3.13t • GIL
+    name: Manylinux on 🐍 3.13 • GIL
```
Comment (henryiii) [inline .github/workflows/ci.yml]: We had this to test free threading (I'm not sure why it has GIL in the title), so I'd go for 3.14t.

```suggestion
    name: Manylinux on 🐍 3.14t
```

File: .github/workflows/ci.yml [hunk 4]
```diff
@@ -257,7 +254,7 @@ jobs:
         run: uv tool install ninja
 
       - name: Configure via preset
-        run: cmake --preset venv -DPYBIND11_CREATE_WITH_UV=python3.13t
+        run: cmake --preset venv -DPYBIND11_CREATE_WITH_UV=python3.13
```
Comment (henryiii) [inline .github/workflows/ci.yml]:
```suggestion
        run: cmake --preset venv -DPYBIND11_CREATE_WITH_UV=python3.14t
```

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -84,7 +84,7 @@ jobs:
             python-version: '3.12'
             cmake-args: -DPYBIND11_TEST_SMART_HOLDER=ON -DPYBIND11_SIMPLE_GIL_MANAGEMENT=ON
           - runs-on: ubuntu-latest
-            python-version: '3.13t'
+            python-version: '3.13'
```
Comment (henryiii) [inline .github/workflows/ci.yml]:
```suggestion
            python-version: '3.14t'
```

**Comment by colesbury** [comment]
I think https://github.com/pybind/pybind11/pull/5973 should fix the occasional deadlock @rwgk saw

**Comment by rwgk** [comment]
The failure below is reproducible (not a flake) and almost certainly related to commit 91189c9242e787922d26ca467710dcc494871b82 here.

For comparison, running the [CI for current master comes back all green](https://github.com/pybind/pybind11/actions/runs/21558546929/).

I also verified that #5972 does not fix it (@b-pass @XuehaiPan for visibility), but there is a second failure of the same kind:
* [CI / 🐍 (ubuntu-latest, 3.14t, -DCMAKE_CXX_STANDARD=20 -DPYBIND11_DISABLE_HANDLE_TYPE_NAME_DEFAULT_I... / 🧪 (pull_request)](https://github.com/pybind/pybind11/actions/runs/21558860079/job/62119622188?pr=5979)Failing after 5m
* [CI / Manylinux on 🐍 3.14t (pull_request)](https://github.com/pybind/pybind11/actions/runs/21558860079/job/62119621986?pr=5979)Failing after 6m

I'll undo 91189c9242e787922d26ca467710dcc494871b82 in hopes that it'll allow us to get this PR merged.

___

[CI / Manylinux on 🐍 3.14t (pull_request)](https://github.com/pybind/pybind11/actions/runs/21557941525/job/62118841785?pr=5971)Failing after 6m

```
=================================== FAILURES ===================================
__________________ test_import_in_subinterpreter_concurrently __________________

    @pytest.mark.skipif(
        sys.platform.startswith("emscripten"), reason="Requires loadable modules"
    )
    @pytest.mark.skipif(not CONCURRENT_INTERPRETERS_SUPPORT, reason="Requires 3.14.0b3+")
    def test_import_in_subinterpreter_concurrently():
        """Tests that importing a module in multiple subinterpreters concurrently works correctly"""
>       check_script_success_in_subprocess(
            PREAMBLE_CODE
            + textwrap.dedent(
                """
                import gc
                from concurrent.futures import InterpreterPoolExecutor, as_completed
    
                futures = future = None
                with InterpreterPoolExecutor(max_workers=16) as executor:
                    futures = [executor.submit(test) for _ in range(32)]
                    for future in as_completed(futures):
                        future.result()
                del futures, future, executor
    
                for _ in range(5):
                    gc.collect()
                """
            )
        )


../../tests/test_multiple_interpreters.py:437: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

code = "def test():\n    import sys\n\n    sys.path.insert(0, '/__w/pybind11/pybind11/build/tests')\n\n    import collections...as_completed(futures):\n        future.result()\ndel futures, future, executor\n\nfor _ in range(5):\n    gc.collect()"

    def check_script_success_in_subprocess(code: str, *, rerun: int = 8) -> None:
        """Runs the given code in a subprocess."""
E               # The expected objects are dynamically imported from `collections`.
E               assert objects[-2:] == expected[-2:], (
E                   f"Expected heap objects {expected[-2:]!r}, got {objects[-2:]!r}."
E               )
E           
E               assert hasattr(m, 'MyClass'), "Module missing MyClass"
E               assert hasattr(m, 'MyGlobalError'), "Module missing MyGlobalError"
E               assert hasattr(m, 'MyLocalError'), "Module missing MyLocalError"
E               assert hasattr(m, 'MyEnum'), "Module missing MyEnum"
E           
E           import gc
E           from concurrent.futures import InterpreterPoolExecutor, as_completed
E           
E           futures = future = None
E           with InterpreterPoolExecutor(max_workers=16) as executor:
E               futures = [executor.submit(test) for _ in range(32)]
E               for future in as_completed(futures):
E                   future.result()
E           del futures, future, executor
E           
E           for _ in range(5):
E               gc.collect()
E           ```
E           
E           Output:
E           Exception: Traceback (most recent call last):
E             File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
E             File "<frozen importlib._bootstrap>", line 1333, in _find_and_load_unlocked
E             File "<frozen importlib._bootstrap>", line 1267, in _find_spec
E             File "<frozen importlib._bootstrap_external>", line 1292, in find_spec
E             File "<frozen importlib._bootstrap_external>", line 1266, in _get_spec
E             File "<frozen importlib._bootstrap_external>", line 1369, in find_spec
E             File "<frozen importlib._bootstrap_external>", line 1412, in _fill_cache
E           BlockingIOError: [Errno 11] Resource temporarily unavailable: '/opt/python/cp314-cp314t/lib/python3.14t/concurrent'
E           
E           The above exception was the direct cause of the following exception:
E           
E           concurrent.interpreters.NotShareableError: object could not be unpickled
E           
E           The above exception was the direct cause of the following exception:
E           
E           Traceback (most recent call last):
E             File "<string>", line 45, in <module>
E               future.result()
E               ~~~~~~~~~~~~~^^
E             File "/opt/python/cp314-cp314t/lib/python3.14t/concurrent/futures/_base.py", line 443, in result
E               return self.__get_result()
E                      ~~~~~~~~~~~~~~~~~^^
E             File "/opt/python/cp314-cp314t/lib/python3.14t/concurrent/futures/_base.py", line 395, in __get_result
E               raise self._exception
E             File "/opt/python/cp314-cp314t/lib/python3.14t/concurrent/futures/thread.py", line 86, in run
E               result = ctx.run(self.task)
E             File "/opt/python/cp314-cp314t/lib/python3.14t/concurrent/futures/interpreter.py", line 84, in run
E               return self.interp.call(do_call, self.results, *task)
E                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/opt/python/cp314-cp314t/lib/python3.14t/concurrent/interpreters/__init__.py", line 238, in call
E               return self._call(callable, args, kwargs)
E                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/opt/python/cp314-cp314t/lib/python3.14t/concurrent/interpreters/__init__.py", line 220, in _call
E               res, excinfo = _interpreters.call(self._id, callable, args, kwargs, restrict=True)
E                              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           concurrent.interpreters.NotShareableError: func not shareable

_          = 1
code       = "def test():\n    import sys\n\n    sys.path.insert(0, '/__w/pybind11/pybind11/build/tests')\n\n    import collections...as_completed(futures):\n        future.result()\ndel futures, future, executor\n\nfor _ in range(5):\n    gc.collect()"
rerun      = 8

../../tests/test_multiple_interpreters.py:284: RuntimeError
=========================== short test summary info ============================
```

File: include/pybind11/detail/internals.h [hunk 6]
```diff
@@ -238,6 +239,23 @@ class pymutex {
...
+    pymutex &mutex;
```
Comment (Skylion007) [inline include/pybind11/detail/internals.h:243]: Okay, interesting to me the RAII doesn't own the mutex and the ctor takes a mutable reference.

Comment (rwgk) [reply include/pybind11/detail/internals.h:243]: This looks correct to me, based on this Cursor-generated analysis:

This is the standard lock-guard pattern: the RAII object owns the critical-section lifetime, not the mutex. It takes a
  non-const ref because locking mutates the mutex (and `PyCriticalSection_BeginMutex` needs a mutable `PyMutex). The mutex itself is owned by the internals and outlives the guard:

https://github.com/pybind/pybind11/blob/0080cae388f6e6ec8d12b51138c6389e0a0c6e9b/include/pybind11/detail/internals.h#L230-L239

**Review by rwgk — APPROVED** [review]

**Comment by rwgk** [comment]
Not rerunning the CI, because the exact same state was tested under #5980 already.

File: include/pybind11/detail/internals.h (hunk 1 above)
Comment (XuehaiPan) [reply include/pybind11/detail/internals.h]: Could we have a guard with `#if defined(Py_GIL_DISABLED) && defined(PY_VERSION_HEX) && PY_VERSION_HEX >= ...` here? It is causing a compilation error with Python 3.13t. In addition, the function `PyCriticalSection_BeginMutex` was added in Python 3.14.0rc1 and Python 3.15.0a1.

- python/cpython#135899

Comment (rwgk) [reply include/pybind11/detail/internals.h]: > It is causing a compilation error with Python 3.13t.

Ah, looks like we were too efficient dropping 3.13t. We should keep it working at the level before this PR for the v3.0.2 release, then fully drop 3.13t support after the release. @XuehaiPan could you help starting a PR for that? Just the code changes, to be sure it works for you. I can help adding back one 3.13t job.

Comment (XuehaiPan) [reply include/pybind11/detail/internals.h]: I opened #5981
