### PR TITLE
fix: avoiding usage of _ if already defined

### LINKED ISSUE #3401: [BUG]: Underscore function conflicts with gettext common usage
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

The use of `_` as a function in `detail/descr.h` conflicts with the common macro usage of `_()` to denote `gettext()`.

The use of `_` for translation is baked into multiple programs, e.g. wxFormBuilder to generate code for frameworks (wxWidgets) that expect the macro.

While this macro is only a suggestion in the gettext manual [1], it is built into expectations[2][3][4][5].

Since the pybind11 usage is internal, would we be able to rename the pybind11 functions from `_` to something similarly short like `x`?

[1] http://www.gnu.org/software/gettext/manual/gettext.html#Overview
[2] https://forums.wxwidgets.org/viewtopic.php?t=19062
[3] https://stackoverflow.com/q/15244397/995714
[4] https://stackoverflow.com/q/15244397/995714
[5] https://stackoverflow.com/questions/3336056/underscore-before-the-format-string

### Reproducible example code

```text
#define _(s) gettext(s)
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(gettext_test, m) {
    m.attr("test") = "test";
}
```

### PR DESCRIPTION
**Pull request by henryiii**
## Description

Closes #3401 by avoiding using a raw `_`.

## Suggested changelog entry:

```rst
* Replace ``_`` with ``const_name`` in internals, avoid defining ``pybind::_`` if ``_`` defined as macro (common gettext usage).
```

### CODE REVIEW

File: include/pybind11/detail/descr.h [hunk 1]
```diff
@@ -53,9 +53,16 @@ constexpr descr<N1 + N2, Ts1..., Ts2...> operator+(const descr<N1, Ts1...> &a, c
     return plus_impl(a, b, make_index_sequence<N1>(), make_index_sequence<N2>());
 }
 
+template <size_t N>
+constexpr descr<N - 1> const_str(char const(&text)[N]) { return descr<N - 1>(text); }
+constexpr descr<0> const_str(char const(&)[1]) { return {}; }
+
+// The "_" might be defined as a macro - don't define it if so.
+#ifndef _
```
Comment (Skylion007) [inline include/pybind11/detail/descr.h:61]: Do we should add a check to ensure people don't accidentally add the old syntax back into PyBind11 code.

Comment (henryiii) [reply include/pybind11/detail/descr.h:61]: We could probably just add a define to a CMake job? `-D_=1` for example?

**Comment by jagerman** [comment]
This needs a doc update, too: the `_` is still used in the examples in https://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html

File: include/pybind11/detail/descr.h (hunk 1 above)
Comment (rwgk) [reply include/pybind11/detail/descr.h:61]: @Skylion007 What kind of check did you have in mind?

The only thing I can think of is something like:
```
#ifndef PYBIND11_DO_NOT_DEFINE_UNDERSCORE
#ifndef _
...
#endif
#endif
```

Only loosely related, would this work?
```
#define _ const_str
```

Just for background / FYI:

I love this PR, although it will be a one or two day cleanup job for me to replace `_` with `const_str` throughout Google's code base (including imported 3rd party code). After I'm done I'd add `PYBIND11_DO_NOT_DEFINE_UNDERSCORE` to our central build rule, to ensure the underscore cannot be used anymore.

**Comment by henryiii** [comment]
Do we want to change the docs over? I think it's more readable, so I'd be in favor. We can leave `_` available indefinitely due to its previous prevalence.

**Comment by rwgk** [comment]
> Do we want to change the docs over? I think it's more readable, so I'd be in favor. We can leave `_` available indefinitely due to its previous prevalence.

I'm strongly in favor if changing the docs to `const_str`. I'm really glad to see this change, the `_` is so easy to overlook, so difficult to pin-point, and gives no clue to what it's for.

File: include/pybind11/detail/descr.h (hunk 1 above)
Comment (rwgk) [reply include/pybind11/detail/descr.h:61]: Got it, thanks; sorry the history wasn't apparent to me.

A define similar to `PYBIND11_DO_NOT_DEFINE_UNDERSCORE` will be very important for my purposes, to guard against backsliding. I could patch it in when importing pybind11 from github, but I believe it will be useful in other environments, too, and it's just a couple lines extra in the code, and maybe one or two sentences in the changelog.

Comment (rwgk) [reply include/pybind11/detail/descr.h:61]: Hi @henryiii, did you see my comment above? Does `PYBIND11_DO_NOT_DEFINE_UNDERSCORE` work for everybody? I'd be happy to add that here.

Comment (henryiii) [reply include/pybind11/detail/descr.h:61]: I don't see the point of adding yet another configuration option when you can just define `-D_=1` (which is the original problem with this) and that works fine? You could even do:

```c++
#define _
#include <pybind11/pybind11.h>
#undef _
```

Comment (rwgk) [reply include/pybind11/detail/descr.h:61]: Actually at 2nd thought, what I really want is an opt-in rather than an opt-out.
I'll just apply an automatic patch when importing from github.

About my other question, do we need to repeat the complicated `const_str` code? Is there a catch with this?
```
#ifndef _
#define _ const_str
#endif
```

I just tried it quickly locally and it seems to work.

Comment (henryiii) [reply include/pybind11/detail/descr.h:61]: Because you should always avoid defines if at all possible. The problem here is that _other_ people are defining `_`; we are not, this was and is `pybind11::_`. We are trying to play nice with bad actors, not become one ourselves! :)

Comment (rwgk) [reply include/pybind11/detail/descr.h:61]: In that case a comment would be useful, e.g.
```
// Repeating the const_str code to avoid introducing a #define.
```

**Review by rwgk — APPROVED** [review]

**Review by rwgk — APPROVED** [review]
Randomly crossed my mind:

`const_char_array` would be a more truthful / expressive name.

`py::str` is something completely different from `py::detail::const_str`.

**Comment by jagerman** [comment]
> Randomly crossed my mind:
> 
> `const_char_array` would be a more truthful / expressive name.

Kind of, but the point of this wrapper isn't to be a const char array, it's meant only to be a compile-time static name for a class, and being a const char array just happens to be the current implementation detail.  So perhaps `"py::type_name"` or something along that line would be a better choice?

File: include/pybind11/cast.h [hunk 2]
```diff
@@ -208,7 +208,7 @@ struct type_caster<T, enable_if_t<std::is_arithmetic<T>::value && !is_std_char_t
         return PyLong_FromUnsignedLongLong((unsigned long long) src);
     }
 
-    PYBIND11_TYPE_CASTER(T, _<std::is_integral<T>::value>("int", "float"));
+    PYBIND11_TYPE_CASTER(T, const_str<std::is_integral<T>::value>("int", "float"));
```
Comment (jagerman) [inline include/pybind11/cast.h:211]: I think we should add one test that keeps the `_` that only gets built/tested when `_` is not externally defined (so that we still test backwards compatibility for existing code still using `_`).

**Comment by henryiii** [comment]
I think the overlap between `py::detail::const_str` and `py::str` is fine - there can't be a const version of `py::str`, since it's a Python object, and you really don't see the `py::detail` part, it's always just `const_str` in the type caster. It's important to keep it fairly clear and short. `_` is a bit too much, but `const_char_array` would be too long. (And, eventually, it might be able to use a constexpr string, perhaps?)

`const_name` or `static_name` or `static_str` are ideas, though.

I can add a test. I'm wondering if adding a `_` define is tripping up Boost.

**Comment by rwgk** [comment]
> const_name or static_name or static_str are ideas, though.

`const_name` sounds good to me, in line with Jason's idea to emphasize high level vs impl detail.

`static` has so many meanings already ... thinking, better not.

**Comment by henryiii** [comment]
So `const_str`, `const_name`, and `type_name` (which I missed from before).

**Comment by rwgk** [comment]
Const name is my strong favorite

(Typing on my phone)

**Review by rwgk — APPROVED** [review]
I just took another look. Perfect, thanks a lot for doing this!

**Comment by henryiii** [comment]
Can I get one more approval? @jagerman, @Skylion007, or someone else?

**Review by jagerman — APPROVED** [review]
Looks good to me.
