### PR TITLE
Fix crash in `gil_scoped_acquire`

### LINKED ISSUE #5827: [BUG]: Crash in free-threaded Python when destructors acquire and release the GIL
### Required prerequisites

- [x] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

852a4b5010e339930e974e03eafdaaa3f6f32c36

### Problem description

In the free-threaded build, `PyThreadState_Clear` removes the thread from the biased reference counting table, which can cause finalizers to be called. Those finalizers can themselves destroy the thread state, leaving `PyThreadState_Clear` with a dangling pointer.

This was reported in python/cpython#119585 and fixed in python/cpython#119753.

### Reproducible example code

```text
// repro.cpp

#include <barrier>
#include <pybind11/pybind11.h>
#include <thread>

namespace py = pybind11;

void do_stuff(py::type cls) {
  py::handle obj;

  std::barrier barrier{2};
  std::jthread t1{[&]() {
    py::gil_scoped_acquire gil;
    obj = cls().release();
    barrier.arrive_and_wait();
  }};
  std::jthread t2{[&]() {
    py::gil_scoped_acquire gil;
    barrier.arrive_and_wait();
    // ob_ref_shared becomes negative; transition to the queued state
    obj.dec_ref();
  }};
}

PYBIND11_MODULE(repro, m, py::mod_gil_not_used()) {
  m.def("do_stuff", &do_stuff);
  m.def("finalizer", []() { py::gil_scoped_acquire gil; });
}

// main.py

import repro

class Foo:
    def __del__(self):
        repro.finalizer()

repro.do_stuff(Foo)
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by rostan-t**
## Description

Increase `gilstate_counter` before calling `PyThreadState_Clear` in `gil_scoped_acquire` to prevent finalizers to try to create and destroy a new thread state while the current thread state is being cleared.

Fixes #5827

## Suggested changelog entry:

Fix crash that can occur when finalizers acquire and release the GIL.

----
📚 Documentation preview 📚: https://pybind11--5828.org.readthedocs.build/

### CODE REVIEW

File: tests/test_thread.cpp [hunk 1]
```diff
@@ -15,6 +15,11 @@
 #include <chrono>
 #include <thread>
 
+#if defined(PYBIND11_CPP20) && defined(__has_include) && __has_include(<barrier>)
+#    define PYBIND11_HAS_BARRIER 1
+#    include <barrier>
+#endif
+
```
Comment (rwgk) [inline tests/test_thread.cpp]: Could you please move this somewhere around here?

https://github.com/pybind/pybind11/blob/852a4b5010e339930e974e03eafdaaa3f6f32c36/include/pybind11/detail/common.h#L97

I think `PYBIND11_HAS_STD_BARRIER` would be ideal (similar to the `PYBIND11_HAS_STD_LAUNDER` that we have already).

File: include/pybind11/gil.h [hunk 2]
```diff
@@ -120,7 +120,11 @@ class gil_scoped_acquire {
                 pybind11_fail("scoped_acquire::dec_ref(): internal error!");
             }
 #    endif
+            // Make sure that PyThreadState_Clear is not recursively called by finalizers.
+            // See issue #5827
+            ++tstate->gilstate_counter;
```
Comment (rwgk) [inline include/pybind11/gil.h:125]: Totally not sure: Is there any point in guarding this with `#if defined(...)` for certain Python versions and `Py_GIL_DISABLED`?

File: tests/test_thread.cpp [hunk 3]
```diff
@@ -67,6 +71,39 @@ TEST_SUBMODULE(thread, m) {
...
+            obj.dec_ref();
+        }};
+
+        // jthread is not supported by Apple Clang
+        thread1.join();
+        thread2.join();
+    });
+#endif
+
+    m.attr("has_barrier") =
```
Comment (rwgk) [inline tests/test_thread.cpp]: In other places we use a pattern that would be `defined_PYBIND11_HAS_STD_BARRIER` here.

(It makes it a little easier to pin-point all things connected to `PYBIND11_HAS_STD_BARRIER` across Python and C++ code.)

**Review by rwgk — COMMENTED** [review]
I just added this a couple days ago (PR #5822), to git rid of very frequent failures under macOS / free-threaded that nobody had the time to debug:

https://github.com/pybind/pybind11/blob/852a4b5010e339930e974e03eafdaaa3f6f32c36/tests/test_gil_scoped.py#L205-L209

WDYT about removing that in this PR? — So that we see immediately if your fix helps with that, too. If not, we can put that code back in a follow-on PR.

File: include/pybind11/gil.h (hunk 2 above)
Comment (rostan-t) [reply include/pybind11/gil.h:125]: I focused on free-threading here but I think that the issue can also occur in destructors of thread-local variables in the regular build.

**Comment by colesbury** [comment]
FWIW, this LGTM

File: tests/test_thread.cpp (hunk 1 above)
Comment (rostan-t) [reply tests/test_thread.cpp]: Fixed by 056a605a1a11fdb5c9c28cc7eb15b1562e29289b

File: tests/test_thread.cpp (hunk 3 above)
Comment (rostan-t) [reply tests/test_thread.cpp]: Fixed by d2bd9aaf931348cd468768efc31ba48371de0402

**Review by rwgk — APPROVED** [review]
Thanks @colesbury for reviewing this PR!

Thanks @rostan-t for the fix!
