### PR TITLE
Fix casts to void*

### LINKED ISSUE #4117: [BUG]: void value not ignored as it ought to be
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

the bind code like this :
```cpp
#include <pybind11/pybind11.h>
#include <iostream>
namespace py = pybind11;
using std::cout;
using std::endl;
class Animal {
public:
    virtual ~Animal() { }
    virtual void* go() = 0;
};

class PyAnimal : public Animal {
public:
    /* Inherit the constructors */
    using Animal::Animal;
    /* Trampoline (need one for each virtual function) */
    void* go() override {
        PYBIND11_OVERRIDE_PURE(
            void*, /* Return type */
            Animal,      /* Parent class */
            go,          /* Name of function in C++ (must match Python name) */
        );
    }
};

PYBIND11_MODULE(example, m) {
    py::class_<Animal, PyAnimal /* <--- trampoline*/>(m, "Animal")
        .def(py::init<>())
        .def("go", &Animal::go);
}
```

use pybind11 2.10.0,get error below:

```
example.cpp: In member function ‘virtual void* PyAnimal::go(int)’:
example.cpp:21:9: error: void value not ignored as it ought to be
   21 |         PYBIND11_OVERRIDE_PURE(
      |         ^~~~~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

but use pybind 2.9.2 is ok ，how to deal with it ？？

### Reproducible example code

_No response_

### PR DESCRIPTION
**Pull request by Lalaland**
## Description

The current code is broken for safe casts to void* as those are incorrectly converted to casts to void. This fixes the problem.

Fixes #4117, needed for #4125

This is a reopened version of #4273 with some minor test changes. Closes #4117.

## Suggested changelog entry:

```rst
* Fix support for safe casts to void* (regression in 2.10.0)
```

### CODE REVIEW

**Review by henryiii — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
Actually, hold on confused whether this or #4274 is correct. This is slightly different: [std::is_void](https://en.cppreference.com/w/cpp/types/is_void) is equivalent to std::remove_cv_t not std::remove_cvref_t. Which one is actually appropiate here? Which cast should be used for void pointer and references @rwgk @Lalaland ?

**Comment by rwgk** [comment]
> Which cast should be used for void pointer and references @rwgk @Lalaland ?

If we go by testing, all tests pass with 4 different variants now, from that viewpoint any of those is fine.

The best way to answer the question above is to create a full set of tests (c v ref), see what compilers actually accept, then make the tests work the way we want them to. (In this case that's probably only a very small effort.)

From an elegance viewpoint, `std::is_void` looks nicest.

**Comment by Lalaland** [comment]
> Actually, hold on confused whether this or https://github.com/pybind/pybind11/pull/4274 is correct. This is slightly different: [std::is_void](https://en.cppreference.com/w/cpp/types/is_void) is equivalent to std::remove_cv_t not std::remove_cvref_t. Which one is actually appropiate here? Which cast should be used for void pointer and references @rwgk @Lalaland ?

References to void are illegal, so std::remove_cv_t and std::remove_cvref_t are equivalent. So std::is_void is preferred.

File: include/pybind11/cast.h [hunk 1]
```diff
@@ -1179,11 +1179,9 @@ enable_if_t<cast_is_temporary_value_reference<T>::value, T> cast_safe(object &&)
     pybind11_fail("Internal error: cast_safe fallback invoked");
 }
 template <typename T>
-enable_if_t<std::is_same<void, intrinsic_t<T>>::value, void> cast_safe(object &&) {}
+enable_if_t<std::is_void<T>::value, void> cast_safe(object &&) {}
```
Comment (laramiel) [inline include/pybind11/cast.h:1182]: Yeah, is std::is_void<T> is more elegant.

**Comment by laramiel** [comment]
Yes, as noted in https://github.com/pybind/pybind11/pull/3861, references to void are not allowed in C++, and `std::is_void<T>` is essentially the shorthand for what I wrote there.

https://en.cppreference.com/w/cpp/types/is_void

**Review by rwgk — APPROVED** [review]
Awesome, thanks @Lalaland and @laramiel! I'll merge this now.
