### PR TITLE
fix: make gil_safe_call_once thread-safe in free-threaded CPython

### LINKED ISSUE #5245: [BUG]: gil_safe_call_once_and_store is not NoGil thread safe.
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

0e2c3e5

### Problem description

In the function, 
https://github.com/pybind/pybind11/blob/ccefee4c3187c2892fcf4590b1bbc850134b84bb/include/pybind11/gil_safe_call_once.h#L51-L59

`is_initialized_` is read outside of the critical section without any synchronization. Which can lead to a race in a NoGil build.

### Reproducible example code

```text
N/A
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by colesbury**
## Description

The "is_initialized_" flags is not protected by the GIL in free-threaded Python, so it needs to be an atomic field.

Fixes #5245

## Suggested changelog entry:

```rst
Make ``gil_safe_call_once_and_store`` thread-safe in free-threaded CPython.
```

### CODE REVIEW

File: include/pybind11/gil_safe_call_once.h [hunk 1]
```diff
@@ -7,6 +7,9 @@
 
 #include <cassert>
 #include <mutex>
+#ifdef Py_GIL_DISABLED
```
Comment (rwgk) [inline include/pybind11/gil_safe_call_once.h:10]: Slight preference for an empty line before the `#ifdef`.

File: include/pybind11/gil_safe_call_once.h [hunk 2]
```diff
@@ -82,7 +85,11 @@ class gil_safe_call_once_and_store {
 private:
     alignas(T) char storage_[sizeof(T)] = {};
     std::once_flag once_flag_ = {};
+#ifdef Py_GIL_DISABLED
```
Comment (rwgk) [inline include/pybind11/gil_safe_call_once.h:88]: Does it work on all platforms like this?

```diff
-    bool is_initialized_ = false;
+#ifdef Py_GIL_DISABLED
+    std::atomic_bool
+#else
+    bool
+#endif
+        is_initialized_{false};
```

**Review by rwgk — APPROVED** [review]

File: include/pybind11/gil_safe_call_once.h (hunk 2 above)
Comment (colesbury) [reply include/pybind11/gil_safe_call_once.h:88]: Yes, I think that should work.

**Comment by rwgk** [comment]
Hi @colesbury, considering that Python 3.13.0rc1 is out, we (me, @henryiii, @EthanSteinberg ) are thinking it may be useful to make another pybind11 release, with this PR included. We are wondering: Is there anything else obvious (from your vantage point) that we could/should do in pybind11, before making a release?

**Comment by colesbury** [comment]
No, I can't think of anything else

**Comment by EthanSteinberg** [comment]
@colesbury I'm a bit worried about the logic in https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/internals.h#L498 under free-threading and I was hoping I could get your help to double check that everything is thread safe.

internals is a global singleton struct shared across all pybind11 modules. get_internals() either retrieves that current global singleton or creates a new one.

I'm a bit worried about double initialization, where two copies of internals would be created by multiple modules being imported/initalized in different threads.

https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/internals.h#L520-L524 are the key problematic lines where we retrieve the current global, and initialize it if necessary.

The problem is that if two threads hit those lines at the same time, both threads could see that internals and null and both threads could initialize internals, which would lead to two copies.

Currently this is protected via the GIL (https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/internals.h#L505), but does that work with the new free threading code?

**Comment by colesbury** [comment]
I think it would be better if we made the initialization in `get_internals()` explicitly thread-safe, but it's unlikely to cause problems because the free-threaded build temporarily enables the GIL when importing C extensions.

Do you want to create an issue for this?

**Comment by henryiii** [comment]
Another question (based on a question from @EthanSteinberg in separate communication): would it make sense for `gil_scoped_acquire` to take our lock? Code placed in a `gil_scoped_acquire` block expects to have a lock.

**Comment by colesbury** [comment]
No, I think `gil_scoped_acquire` should just call `PyGILState_Ensure` or equivalent. If extensions want a global lock, they can skip setting `py::mod_gil_not_used`.

**Comment by EthanSteinberg** [comment]
@colesbury  Thanks for confirming that the GIL is enabled during module initialization, so this is probably not a concern. 

I don't know if it makes sense to make an issue now for this. Instead, let me write a PR next weekend that just adds some comments to the code pointing out why the module initialization GIL behavior allows that code to be safe even with free threading.

**Comment by colesbury** [comment]
I'd rather not rely on the GIL behavior during module initialization. Additionally, at least in theory, I think `get_internals()` could be called for the first time after the C API extension was initialized.

**Comment by rwgk** [comment]
> I'd rather not rely on the GIL behavior during module initialization. Additionally, at least in theory, I think `get_internals()` could be called for the first time after the C API extension was initialized.

I'm not sure if it's helpful, but JIC, `get_internals()` is called from here (`PYBIND11_MODULE()` macro):

* https://github.com/pybind/pybind11/blob/fc59f4e6e508f28c0e2896937660b9eae0f5ea51/include/pybind11/detail/common.h#L489

**Comment by EthanSteinberg** [comment]
@colesbury @rwgk  I created an issue to track / solve this https://github.com/pybind/pybind11/issues/5316
