### PR TITLE
bugfix: Keep registered types until after Py_Finalize(). Fix #4459

### LINKED ISSUE #4459: [BUG]: Python atexit broken with pybind11 version >= 2.9.2
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.2

### Problem description

We want to upgrade from pybind11 release 2.9.0 to 2.10.2, but we encountered an issue in the Python atexit (https://docs.python.org/3/library/atexit.html) functions, that our custom types are not registered anymore. With delta debugging we found that this PR caused the issue: https://github.com/pybind/pybind11/pull/3744

In my opinion the
```
    detail::get_local_internals().registered_types_cpp.clear();    
    detail::get_local_internals().registered_exception_translators.clear();
```

calls should be after the _Py_Finalize_ function call.

When I change the orders of those function calls, the problem is gone.

### Reproducible example code

_No response_

### Is this a regression? Put the last known working version here if it is.

2.9.1

### PR DESCRIPTION
**Pull request by Skylion007**
## Description
Fix #4459 . Keep types registered until after atexit is called.

TODO / help wanted: unit test exercising the atexit situation.

## Suggested changelog entry:

```rst
* Fix bug where cpptypes were unregistered before atexit was called.
```

### CODE REVIEW

File: include/pybind11/embed.h [hunk 1]
```diff
@@ -254,13 +254,15 @@ inline void finalize_interpreter() {
     if (builtins.contains(id) && isinstance<capsule>(builtins[id])) {
         internals_ptr_ptr = capsule(builtins[id]);
     }
+
+    Py_Finalize();
+
     // Local internals contains data managed by the current interpreter, so we must clear them to
     // avoid undefined behaviors when initializing another interpreter
+    // Must be cleared after Py_Finalize() so atexit and other hooks can use registered_types
```
Comment (rwgk) [inline include/pybind11/embed.h:262]: // Must be cleared only after Py_Finalize() so atexit and other hooks can still use use registered_types

?

Extra "only" and "still", to emphasize the importance.

**Review by rwgk — APPROVED** [review]
I'm OK to let the testing slip, in the interest of getting the fix in sooner rather than later, but it would be best to mention that clearly in the PR description, e.g.:

TODO / help wanted: unit test exercising the atexit situation.
