### PR TITLE
Fix `smart_holder` multiple/virtual inheritance bugs in `shared_ptr` and `unique_ptr` to-Python conversions

### LINKED ISSUE #5786: [BUG]: Using smart_holder in virtual inheritance relationship error
### Required prerequisites

- [x] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

3.0.0

### Problem description

The following code about virtual inheritance relationship , i use `smart_holder` instead of `std::shared_ptr`.  
```
class Animal {
public:
  virtual std::shared_ptr<Animal> clone() const = 0;
  virtual ~Animal() = default;
};

class Cat : virtual public Animal {
public:
  virtual ~Cat() override = default;
};

class Tiger : virtual public Cat {
public:
  Tiger() = default;
  Tiger(const Tiger &) = default;
  ~Tiger() override = default;
  std::shared_ptr<Animal> clone() const override {
    return std::make_shared<Tiger>(*this);
  }
};

void bind_animals(pybind11::module_ &module) {

  pybind11::class_<Animal, pybind11::smart_holder>(module, "Animal");

  pybind11::class_<Cat, Animal, pybind11::smart_holder>(module, "Cat");

  pybind11::class_<Tiger, Cat, pybind11::smart_holder>(
      module, "Tiger", pybind11::multiple_inheritance())
      .def(pybind11::init<>())
      .def("clone", &Tiger::clone);
}
```
In python code:
```
tiger = Tiger()
tiger.clone()
```
An error occurred：
```
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```
But it is ok to use `std::shared_ptr` as `py::class_` holder. Are there problems with my usage of the `smart_holder`.
Can anyone help me with this? It's urgent. Thank you very much!

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by rwgk**
## Description
Closes #5786.

This PR fixes **two independent bugs** in the `smart_holder` machinery, both exposed by new tests involving virtual inheritance.

## 1. Fix in `pybind11/detail/type_caster_base.h`
The return-value caster for `std::shared_ptr<T>` was incorrectly using `src.get()` (the most-derived pointer) instead of `st.first` (the adjusted subobject pointer appropriate for the registered `tinfo`).  
On MSVC with virtual inheritance, this mismatch led to passing an `Animal*` (see below) to `register_instance` when binding `Tiger`, which caused the virtual-base offset walker to dereference a bogus vbptr.  
This is the bug reported in #5786. Using `st.first` ensures the correct subobject is registered.

## 2. Fix in `pybind11/detail/struct_smart_holder.h`
`smart_holder::from_unique_ptr` was storing the *subobject* pointer as the owned resource in its control block. Under MSVC, destroying through that misaligned pointer caused NX faults in the virtual destructor path.  
The fix mirrors the `shared_ptr` path: always own the real `T*` object start with the deleter, and, if needed, create an aliasing `shared_ptr<void>` at the subobject pointer for registration/identity.

## Tests
- The original **Animal–Cat–Tiger** reproducer from #5786 is kept as a targeted regression test. It fails reliably only on MSVC, which is why it is important to keep it.
- A new **Diamond virtual-inheritance** test (`test_class_sh_mi_thunks`) was added. This was designed to also fail on Linux/Clang/GCC *without* the fix (not just on MSVC). Indeed, the diamond case fails across all `ci.yml` jobs and several `tests-cibw.yml` jobs pre-fix, and passes after fix (see [comment](https://github.com/pybind/pybind11/pull/5836#issuecomment-3289311423)).
- The diamond test was trivially extended to exercise `smart_holder_from_unique_ptr`, which immediately exposed the second bug. That test produced 20 MSVC failures pre-fix ([comment](https://github.com/pybind/pybind11/pull/5836#issuecomment-3289660447)), and passes after the fix.
- A pseudo-test `test_virtual_base_at_offset_0` is included to make it explicit when a compiler/layout places the virtual base at offset 0. This isn’t a true skip, but a way to document in the pytest summary when the test can’t exercise the MI/VI code path. In practice, this skip has never been triggered in any GitHub Actions job.
- Debug-only `assert`s remain in `pybind11/detail/class.h`. They were invaluable during debugging and experimentation, have no impact on non-debug builds, and may be useful again if MI/VI edge cases resurface.

## Context
The changes here are in the same spirit as PR #4380, which fixed earlier oversights in `smart_holder` MI handling. As noted there, MI use cases are uncommon in downstream projects (and even discouraged in some organizations), so coverage has historically been thin. The new tests give us much better confidence that both `shared_ptr` and `unique_ptr` adoption paths are now robust under virtual and multiple inheritance.
___

Full ChatGPT conversation guiding the work on the fixes (very long and involved): https://chatgpt.com/share/68c7950a-61b8-8008-8678-53b96643ce7e

**A lot** of the credit for the fixes goes to ChatGPT 5 Pro

## Suggested changelog entry:

Fixed two `smart_holder` bugs in `shared_ptr` and `unique_ptr` adoption with multiple/virtual inheritance:

* `shared_ptr` to-Python caster now registers the correct subobject pointer (fixes #5786).

* `unique_ptr` adoption now owns the proper object start while aliasing subobject pointers for registration, fixing MSVC crashes during destruction.

### CODE REVIEW

**Comment by rwgk** [comment]
CI results @ commit 5f77da3d1bd2466e62847eaefce129b5bffcd152:

**66 failing, 2 skipped, 17 successful checks**

CI: https://github.com/pybind/pybind11/actions/runs/17707681525?pr=5836

[gh_pr_checks_2025-09-14+002918.txt](https://github.com/user-attachments/files/22318659/gh_pr_checks_2025-09-14%2B002918.txt)

**Comment by rwgk** [comment]
CI results @ commit 3620ceb02442817063b2aa26ee623d1f65adba50:

**20 failing, 2 skipped, 63 successful checks**

CI: https://github.com/pybind/pybind11/actions/runs/17713020523?pr=5836

[gh_pr_checks_2025-09-14+091113.txt](https://github.com/user-attachments/files/22321546/gh_pr_checks_2025-09-14%2B091113.txt)

**Comment by rwgk** [comment]
@henryiii This PR is ready for review.

@MannixYang If you get a chance to try this out, please report back.

**Comment by MannixYang** [comment]
@rwgk Thank you very much indeed. Yes, I will give it a try. It should be within the next two days.

**Comment by MannixYang** [comment]
@rwgk Great! This is very useful. My project can now run. Thank you again.

**Comment by rwgk** [comment]
> @rwgk Great! This is very useful. My project can now run. Thank you again.

Thanks a lot for confirming!

**Comment by rwgk** [comment]
Hi @iwanders, is there a chance that you could help reviewing this PR? — I just remembered that you're familiar with the affected code, from your work on #4921 and #4924. The production code changes in this PR are small/surgical.

File: include/pybind11/detail/struct_smart_holder.h [hunk 1]
```diff
@@ -339,22 +339,28 @@ struct smart_holder {
...
+        guarded_delete gd
+            = hld.vptr_is_using_std_default_delete
+                  ? make_guarded_std_default_delete<T>(true)
+                  : make_guarded_custom_deleter<T, D>(std::move(unq_ptr.get_deleter()), true);
+        // Critical: construct owner with pointer we intend to delete
+        std::shared_ptr<T> owner(unq_ptr.get(), std::move(gd));
+        // Relinquish ownership only after successful construction of owner
+        (void) unq_ptr.release();
+
+        // Publish either the subobject alias (for identity/VI) or the full object.
```
Comment (iwanders) [inline include/pybind11/detail/struct_smart_holder.h]: Personally, I'd elaborate a bit in this comment. This part feels a bit like magic to me why this is necessary and fixes a bug when this is used in msvc. I think I understand the problem to be that the shared pointer 'owner' must always point to the start of the entire object (and the deleter operates on that), but that the actual smart holder should 'hold' the subclass, which may not be at the start of the object itself?

File: tests/test_class_sh_mi_thunks.cpp [hunk 2]
```diff
@@ -30,6 +32,107 @@ struct Derived : Base1, Base0 {
...
+    VBase(const VBase &) = default; // silence -Wdeprecated-copy-with-dtor
+    VBase &operator=(const VBase &) = default;
+    VBase(VBase &&) = default;
+    VBase &operator=(VBase &&) = default;
+    virtual ~VBase() = default;
+    virtual int ping() const { return 1; }
+    int vbase_tag = 42; // ensure it's not empty
+};
+
+// Left/right add some weight to steer layout differences across compilers
```
Comment (iwanders) [inline tests/test_class_sh_mi_thunks.cpp]: I'm not sure this matters, but `Left` and `Right` are pretty similar a `long long` is guaranteed to be 64 bits, and the 7 long array is likely going to be padded to 8, which would make them the same size? To me the comment contradicts the code a bit in that sense. Maybe just having any attribute is enough, but if the sizes ought to be different I'd make it very clear, say `char pad_l[4]` and `char pad_r[16]`.

File: include/pybind11/detail/struct_smart_holder.h (hunk 1 above)
Comment (rwgk) [reply include/pybind11/detail/struct_smart_holder.h]: Done: commit 31886ecfdccf88f7116f10f96b5bd32674ff11ea

File: tests/test_class_sh_mi_thunks.cpp (hunk 2 above)
Comment (rwgk) [reply tests/test_class_sh_mi_thunks.cpp]: Done: commit ba89e1dd65e5b21fe098e08db1e7cecf7a0a7264

Here is what ChatGPT is saying:

Good catch — the original comment was misleading, since `char[7]` and `long long` can end up the same size after padding. The real intent is simply to make the virtual bases non-empty and, ideally, asymmetrically sized/aligned so compilers are more likely to give us non-zero subobject offsets. I’ve updated the code to use small but clearly asymmetric paddings (`char[4]` vs `char[16]`, with optional alignment) and clarified the comment to reflect this. The test still works correctly even if a compiler chooses offset 0, since that case is explicitly logged via `test_virtual_base_at_offset_0()`.

___

In Ralf's own words: I was just super happy when the GhatGPT-generated test triggered failures on both Linux and Windows [see [comment from two weeks ago](https://github.com/pybind/pybind11/pull/5836#issuecomment-3289311423)] and didn't look as closely at the test code as you did. However, now I pushed ChatGPT harder, to "really bend things out of shape", but it assured me that the new code is as good as we can make it.

I'll rerun the CI. When it's done I'll look for `test_virtual_base_at_offset_0()` skip messages again. (I think I did that before, although I forgot to log that here.)

**Comment by rwgk** [comment]
Checking for `test_virtual_base_at_offset_0()` `SKIPPED` messages
----------------------------------------------------------------------

CI workflow
------------

https://github.com/pybind/pybind11/actions/runs/18080769590

```
$ grep test_class_sh_mi_thunks.py *.txt | wc -l
691
$ grep SKIPPED *.txt | wc -l
3404
$  grep test_class_sh_mi_thunks.py *.txt | grep SKIPPED | wc -l
0
```
___

CIBW workflow
---------------

https://github.com/pybind/pybind11/actions/runs/18080769566

```
$ grep test_class_sh_mi_thunks.py *.txt | wc -l
4
$ grep SKIPPED *.txt | wc -l
135
$ grep test_class_sh_mi_thunks.py *.txt | grep SKIPPED | wc -l
0
```

File: tests/test_class_sh_mi_thunks.cpp (hunk 2 above)
Comment (iwanders) [reply tests/test_class_sh_mi_thunks.cpp]: > I was just super happy when the GhatGPT-generated test triggered failures on both Linux and Windows

Agreed, that is pretty impressive and definitely speeds things up. Thanks for sharing your ChatGPT conversation btw, I’ve bookmarked that to read through when I’m not on the road. I don’t have much experience using llms, so expect it’ll be educational for me.

Comment (rwgk) [reply tests/test_class_sh_mi_thunks.cpp]: > > I was just super happy when the GhatGPT-generated test triggered failures on both Linux and Windows
> 
> Agreed, that is pretty impressive and definitely speeds things up. Thanks for sharing your ChatGPT conversation btw, I’ve bookmarked that to read through when I’m not on the road. I don’t have much experience using llms, so expect it’ll be educational for me.

My time budget for pybind11 maintenance work has become super tiny. I think without ChatGPT I'd have to give up.

Thanks for your review, this was super helpful.

A couple minutes ago I replaced the `pytest.skip()` with an `assert`, to guarantee test quality in the future. It'd be great if you could take a final look and formally approve if it looks good to you.

Comment (iwanders) [reply tests/test_class_sh_mi_thunks.cpp]: > A couple minutes ago I replaced the pytest.skip() with an assert, to guarantee test quality in the future. 

Good idea, and helpful to have that comment there for future developers that may run into the assert failing. I've approved it!

**Comment by rwgk** [comment]
Thanks a lot @iwanders!
