### PR TITLE
fix: AppleClang 12 warnings

### LINKED ISSUE #2509: [BUG] New warning in AppleClang 12
The following warning is produced in AppleClang 12:

```
../include/pybind11/cast.h:2095:26: warning: loop variable 'a' is always a copy because the range of type 'detail::args_proxy' does not return a reference [-Wrange-loop-analysis]
        for (const auto &a : ap)
                         ^
../include/pybind11/cast.h:2095:14: note: use non-reference type 'pybind11::handle'
        for (const auto &a : ap)
             ^~~~~~~~~~~~~~~
../include/pybind11/cast.h:2127:26: warning: loop variable 'k' is always a copy because the range of type 'pybind11::dict' does not return a reference [-Wrange-loop-analysis]
        for (const auto &k : reinterpret_borrow<dict>(kp)) {
                         ^
../include/pybind11/cast.h:2127:14: note: use non-reference type 'std::__1::pair<pybind11::handle, pybind11::handle>'
        for (const auto &k : reinterpret_borrow<dict>(kp)) {
             ^~~~~~~~~~~~~~~
In file included from ../tests/pybind11_cross_module_tests.cpp:10:
In file included from ../tests/pybind11_tests.h:2:
../include/pybind11/pybind11.h:1497:34: warning: loop variable 'kv' is always a copy because the range of type 'pybind11::dict' does not return a reference [-Wrange-loop-analysis]
                for (const auto &kv : entries) {
                                 ^
../include/pybind11/pybind11.h:1497:22: note: use non-reference type 'std::__1::pair<pybind11::handle, pybind11::handle>'
                for (const auto &kv : entries) {
                     ^~~~~~~~~~~~~~~~
../include/pybind11/pybind11.h:1509:34: warning: loop variable 'kv' is always a copy because the range of type 'pybind11::dict' does not return a reference [-Wrange-loop-analysis]
                for (const auto &kv : entries) {
                                 ^
../include/pybind11/pybind11.h:1509:22: note: use non-reference type 'std::__1::pair<pybind11::handle, pybind11::handle>'
                for (const auto &kv : entries) {
                     ^~~~~~~~~~~~~~~~
../include/pybind11/pybind11.h:1524:34: warning: loop variable 'kv' is always a copy because the range of type 'pybind11::dict' does not return a reference [-Wrange-loop-analysis]
                for (const auto &kv : entries) {
                                 ^
../include/pybind11/pybind11.h:1524:22: note: use non-reference type 'std::__1::pair<pybind11::handle, pybind11::handle>'
                for (const auto &kv : entries) {
                     ^~~~~~~~~~~~~~~~
../include/pybind11/pybind11.h:1538:34: warning: loop variable 'kv' is always a copy because the range of type 'pybind11::dict' does not return a reference [-Wrange-loop-analysis]
                for (const auto &kv : entries)
                                 ^
../include/pybind11/pybind11.h:1538:22: note: use non-reference type 'std::__1::pair<pybind11::handle, pybind11::handle>'
                for (const auto &kv : entries)
                     ^~~~~~~~~~~~~~~~
../include/pybind11/pybind11.h:1626:26: warning: loop variable 'kv' is always a copy because the range of type 'pybind11::dict' does not return a reference [-Wrange-loop-analysis]
        for (const auto &kv : entries)
                         ^
../include/pybind11/pybind11.h:1626:14: note: use non-reference type 'std::__1::pair<pybind11::handle, pybind11::handle>'
        for (const auto &kv : entries)
             ^~~~~~~~~~~~~~~~
7 warnings generated.
```

And two more:

```
[26/43] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_pytypes.cpp.o
../tests/test_pytypes.cpp:131:26: warning: loop variable 'item' is always a copy because the range of type 'pybind11::detail::str_attr_accessor' (aka 'accessor<accessor_policies::str_attr>') does not return a reference [-Wrange-loop-analysis]
        for (const auto &item : o.attr("begin_end")) {
                         ^
../tests/test_pytypes.cpp:131:14: note: use non-reference type 'pybind11::handle'
        for (const auto &item : o.attr("begin_end")) {
             ^~~~~~~~~~~~~~~~~~
1 warning generated.
[28/43] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_operator_overloading.cpp.o
../tests/test_operator_overloading.cpp:116:23: warning: explicitly assigning value of variable of type 'const pybind11::detail::self_t' to itself [-Wself-assign-overloaded]
        .def(py::self -= py::self)
             ~~~~~~~~ ^  ~~~~~~~~
../tests/test_operator_overloading.cpp:120:23: warning: explicitly assigning value of variable of type 'const pybind11::detail::self_t' to itself [-Wself-assign-overloaded]
        .def(py::self /= py::self)
             ~~~~~~~~ ^  ~~~~~~~~
2 warnings generated.
```

### PR DESCRIPTION
**Pull request by henryiii**
Fixing two sets of warnings in AppleClang 12. First is a warning that you can't really take a reference to a temporary object, so this will actually always be a copy, and should be clearly written as such.

Second is a bug where 11.0.0 or 12.0.0 or X.X.0 AppleClang will produce a warning due not passing an if statement. It's just a pragma so it should be safe even if the version doesn't match? CC @EricCousineau-TRI  (I think).

Closes #2509

### CODE REVIEW

File: include/pybind11/cast.h [hunk 1]
```diff
@@ -2092,7 +2092,7 @@ class unpacking_collector {
     }
 
     void process(list &args_list, detail::args_proxy ap) {
-        for (const auto &a : ap)
+        for (auto a : ap)
```
Comment (bstaletic) [inline include/pybind11/cast.h:2095]: In case anyone else wonders "why don't we fix the iterator class", here's why:

- "Iterator" is [this thing](https://github.com/pybind/pybind11/blob/master/include/pybind11/pytypes.h#L836)
- [`operator*`](https://github.com/pybind/pybind11/blob/master/include/pybind11/pytypes.h#L857-L863) returns a [`py::handle`](https://github.com/pybind/pybind11/blob/master/include/pybind11/pytypes.h#L841) which is generally better to copy than to take by reference.
- The iterator stores and mutates `value`, so returning a reference here would be wrong as soon as you advance the iterator.

So this is complete fine.

**Review by bstaletic — APPROVED** [review]

**Review by YannickJadoul — APPROVED** [review]

File: include/pybind11/cast.h (hunk 1 above)
Comment (EricCousineau-TRI) [reply include/pybind11/cast.h:2095]: Meep! I guess I haven't looked what `const_iterator` looks for non-random-access containers in STL :sweat_smile:

From my understanding, your statement of "why don't we fix the iterator class" means "why don't we change `operator*` return `[const] handle&`.

I think there's still question like "what do other libs do for similar patterns?", especially for iterators implemented for something like `std::list`, etc.

Comment (EricCousineau-TRI) [reply include/pybind11/cast.h:2095]: (No action here, to be clear, just wanted to clarify on the comment)

**Review by EricCousineau-TRI — APPROVED** [review]
Thanks for the heads up on the Apple `#ifdef` change!

**Comment by YannickJadoul** [comment]
Thanks for [the extra clarification](https://github.com/pybind/pybind11/pull/2510#pullrequestreview-492041747), @bstaletic & @EricCousineau-TRI!

Given that this is a simple fix, I think it can safely go in.
