### PR TITLE
Fix data race when using shared variables (free threading)

### LINKED ISSUE #5489: [BUG]: Data race when using static variables with free-threaded Python
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

v2.13.6

### Problem description

With free-threaded Python, I get data races when using static class variables defined like this:

```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

class Foo {
};

Foo Bar;

PYBIND11_MODULE(foo, m, py::mod_gil_not_used()) {
    py::class_<Foo>(m, "Foo")
        .def_readonly_static("Bar", &Bar);
}
```

I get multiple kinds of errors when accessing `Foo.Bar` from multiple threads, from segmentation faults to "`pybind11_object_dealloc(): Tried to deallocate unregistered instance!`" exceptions.

Further investigation suggested that it might come from `Foo.Bar` being freed too many times. I'm unsure if it's a pybind11 or CPython issue so I'm posting it here.

### Reproducible example code

```py
import threading

from foo import Foo


def create_foo():
    for _ in range(1000):
        Foo.Bar


# keeping a reference to Foo.Bar prevents the issue from happening
# bar = Foo.Bar

nb_threads = 10
threads = [threading.Thread(target=create_foo) for _ in range(nb_threads)]

for thread in threads:
    thread.start()

for thread in threads:
    thread.join()
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

### PR DESCRIPTION
**Pull request by colesbury**
## Description

In the free threading build, there's a race between wrapper re-use and wrapper deallocation. This can happen with a static variable accessed by multiple threads.

Fixing this requires using some private CPython APIs: _Py_TryIncref and _PyObject_SetMaybeWeakref. The implementations of these functions are included until they're made available as public ("unstable") APIs.

Fixes #5489

## Suggested changelog entry:

```rst
Fix data race in free threaded CPython when accessing a shared static variable.
```

### CODE REVIEW

**Comment by colesbury** [comment]
cc @rostan-t @rwgk

File: include/pybind11/detail/class.h [hunk 1]
```diff
@@ -312,7 +312,31 @@ inline void traverse_offset_bases(void *valueptr,
     }
 }
 
+#ifdef Py_GIL_DISABLED
+static inline void enable_try_inc_ref(PyObject *op) {
+    // TODO: Replace with PyUnstable_Object_EnableTryIncRef when available.
+    // See https://github.com/python/cpython/issues/128844
+    if (_Py_IsImmortal(op)) {
```
Comment (rwgk) [inline include/pybind11/detail/class.h:319]: Would it make sense to rename `op` to `obj`? (Or are there any special requirements for `op` that you want to reflect with the variable name?)

File: include/pybind11/detail/class.h [hunk 2]
```diff
@@ -312,7 +312,31 @@ inline void traverse_offset_bases(void *valueptr,
...
+                &op->ob_ref_shared, &shared, shared | _Py_REF_MAYBE_WEAKREF)) {
+            return;
+        }
+    }
+}
+#endif
+
 inline bool register_instance_impl(void *ptr, instance *self) {
+#ifdef Py_GIL_DISABLED
+    enable_try_inc_ref((PyObject *) self);
```
Comment (rwgk) [inline include/pybind11/detail/class.h:338]: Could you please use
```
reinterpret_cast<PyObject *>(self)
```
?
(for readability; we still have a lot of raw C casts, but C++-style casts are preferred in new or changed code)

File: include/pybind11/detail/type_caster_base.h [hunk 3]
```diff
@@ -249,7 +292,10 @@ PYBIND11_NOINLINE handle find_registered_python_instance(void *src,
         for (auto it_i = it_instances.first; it_i != it_instances.second; ++it_i) {
             for (auto *instance_type : detail::all_type_info(Py_TYPE(it_i->second))) {
                 if (instance_type && same_type(*instance_type->cpptype, *tinfo->cpptype)) {
-                    return handle((PyObject *) it_i->second).inc_ref();
+                    PyObject *wrapper = (PyObject *) it_i->second;
```
Comment (rwgk) [inline include/pybind11/detail/type_caster_base.h:295]: I think
```
auto *wrapper = reinterpret_cast<PyObject *>(it_i->second);
```
will make clang-tidy happy (but I haven't tried it out myself).

File: tests/test_thread.py [hunk 4]
```diff
@@ -47,3 +47,23 @@ def test_implicit_conversion_no_gil():
...
+
+@pytest.mark.skipif(sys.platform.startswith("emscripten"), reason="Requires threads")
+def test_bind_shared_instance():
+    nb_threads = 4
+    b = threading.Barrier(nb_threads)
+
+    def access_shared_instance():
+        b.wait()
+        for _ in range(1000):
+            x = m.EmptyStruct.SharedInstance
```
Comment (rwgk) [inline tests/test_thread.py:60]: Is the explicit `del` here needed? Could this be simplified to

```
        for _ in range(1000):
            m.EmptyStruct.SharedInstance
```

?

I asked ChatGPT and it seems to think the simpler code is equivalent. If that's not correct, could you please add a comment to explain (super terse would be fine)?

**Review by rwgk — COMMENTED** [review]
Thanks for the fix! My comments are all very minor.

File: include/pybind11/detail/class.h (hunk 1 above)
Comment (colesbury) [reply include/pybind11/detail/class.h:319]: No special reason. `op` is just commonly used as a variable name for Python objects in CPython so that's what I'm used to now.

File: tests/test_thread.py (hunk 4 above)
Comment (colesbury) [reply tests/test_thread.py:60]: Yeah, it's effectively the same

Comment (colesbury) [reply tests/test_thread.py]: Hmm... clang-tidy doesn't like the "useless expression":

```

tests/test_thread.py:60:13: B018 Found useless expression. Either assign it to a variable or remove it.
   |
58 |         b.wait()
59 |         for _ in range(1000):
60 |             m.EmptyStruct.SharedInstance
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ B018
61 | 
62 |     threads = [
   |

Found 1 error.
```

Comment (rwgk) [reply tests/test_thread.py:61]: An alternative is:

```
            m.EmptyStruct.SharedInstance  # noqa: B018
```

That would be my preference, but only very slightly so. With your comment it's also immediately obvious that there is nothing special about the `del`.

Please let me know if you prefer to keep this as is. I'll merge this PR when I see that the CI is green.

**Review by rwgk — APPROVED** [review]

**Comment by rwgk** [comment]
(The pypy failure is a flake; we see this very often.)

File: tests/test_thread.py (hunk 4 above)
Comment (colesbury) [reply tests/test_thread.py:61]: I'll update it to use the `# noqa`
