### PR TITLE
Make wrapped C++ functions pickleable

### LINKED ISSUE #1261: Making a C++ function pickleable?
## Issue description

Is there a practical way to make a C++ function pickleable? I want to do this in order to support pickle on my own classes with `__reduce__`.

In more detail, I am wrapping a hierarchy of C++ objects. I have a C++ factory function that will return a shared_ptr to a suitable object in the hierarchy given its serialization (the internal details don't matter to this question):
```
std::shared_ptr<Object> makeObject(std::string const &state);
```

As such it is trivial to use `__reduce__` to add pickling support, and I think `__getstate__` and `__setstate__` would be a lot messier. I would like to add this `Object.__reduce__`:
```
    cls.def("__reduce__", [](Object const &self) {
        auto unpickleArgs = py::make_tuple( self.serialize(false));
        return py::make_tuple(py::cpp_function(makeObject), unpickleArgs);
    });
```

This compiles, and `Object.__reduce__()` runs correctly, but when I try to pickle objects I get this error: `TypeError: can't pickle PyCapsule objects`

I have worked around the problem by creating a functor class that does the same thing as `makeObject` and adding a `__reduce__` method to that functor so it can be pickled:

```
class ObjectMaker {
public:
    ObjectMaker() = default;
    std::shared_ptr<Object> operator()(std::string const &state);
};
...
    py::class_<ObjectMaker, std::shared_ptr<ObjectMaker>> makerCls(mod, "ObjectMaker");
    makerCls.def(py::init<>());
    makerCls.def("__call__", &ObjectMaker::operator());
    makerCls.def("__reduce__", [makerCls](ObjectMaker const &self) {
        return py::make_tuple(makerCls, py::tuple());
    });
```

However, if somebody knows a simple way to add support to my `makeObject` function I could avoid the functor and its messy wrapper.

I have included a simple example below. There is no class hierarchy and so no need for `__reduce__`, but it shows the issue.

### C++ Code
```
#include <pybind11/pybind11.h>

namespace py = pybind11;

class Temp {
public:
    std::string id() { return "a Temp"; }
};

Temp makeTemp() { return Temp(); }

PYBIND11_PLUGIN(temp) {
    py::module mod("temp");

    py::class_<Temp, std::shared_ptr<Temp>> cls(mod, "Temp");
    cls.def(py::init<>());
    cls.def("id", &Temp::id);
    cls.def("__reduce__", [](Temp const &self) {
                return py::make_tuple(py::cpp_function(makeTemp), py::make_tuple());
    });
    return mod.ptr();
}
```
### Python code
```
import pickle
from example import temp

t = Temp()
print(t.id())
print(t.__reduce__())
print(pickle.dumps(t))
```
### Results

This prints:
```
>>> example.Test().__reduce__()
(<built-in method  of PyCapsule object at 0x104381b10>, ())
>>> pickle.dumps(example.Test())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't pickle PyCapsule objects
```

### PR DESCRIPTION
**Pull request by rwgk**
## Description
**This PR requires a `PYBIND11_INTERNALS_VERSION` bump (from `8` to `9`).**
________
Closes #1261

[Full ChatGPT assessment](https://chatgpt.com/share/67d09e7a-d1b0-8008-995d-79860b77169d)

**ChatGPT summary** (with a couple edits)

**Motivation and Importance**

Before this PR, pybind11-bound functions are not pickleable, which creates significant friction for Python users who rely on `pickle` and related serialization mechanisms for common tasks such as:

1. **Parallel and Concurrent Processing**

    Python's `multiprocessing` module depends on pickling to distribute tasks across worker processes. Since pybind11 functions cannot be pickled, users are forced to implement fragile and inefficient workarounds (e.g., passing function names as strings or relying on global state). This limits the usability of pybind11 bindings in parallel and distributed computing frameworks such as `multiprocessing`, `concurrent.futures`, and `joblib`.

2. **Caching and Memoization**

    Libraries like `joblib`, `functools.lru_cache`, and `diskcache` rely on pickle to store function results and enable fast recomputation. The inability to pickle pybind11-bound functions makes it difficult to integrate C++ extensions with these widely used caching mechanisms.

3. **Distributed Computing and Cloud Environments**

    Modern data processing frameworks such as Dask and Ray depend on pickling to serialize tasks and distribute them across clusters. The current pybind11 limitation prevents users from leveraging C++-based functions in these environments without cumbersome workarounds.

4. **Testing and Mocking**

    Serialization of test artifacts and fixtures is a common practice in Python testing frameworks like `pytest`. Non-pickleable pybind11 functions make it difficult to persist test state and mock functions consistently.

5. **General Python Compatibility**

    Python developers expect functions and objects to be pickleable as a baseline feature. The fact that pybind11-bound functions break this expectation creates unnecessary obstacles.

This PR introduces a solution to enable pickling of pybind11-bound functions in a way that is efficient, reliable, and consistent with Python's native serialization semantics. The solution has been tested extensively in large-scale production environments and is designed to maintain backward compatibility and minimal performance overhead. By addressing this long-standing limitation, this PR will significantly improve the usability of pybind11 for parallel processing, distributed systems, caching, and testing — making it easier for developers to integrate C++ extensions into modern Python workflows.
________
________
________
 
**Notes:**

* The `repr()` for pybind11 functions is made much more informative and truthful:

Before this PR:
```
<built-in method simple_callable of PyCapsule object at 0x...>
```

(`PyCapsule` objects do not have methods.)

With this PR:
```
<built-in method simple_callable of pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_1 object at 0x...>
```

* The increase in generated machine code size is very small (using `-DCMAKE_BUILD_TYPE=MinSizeRel`):

Before this PR:
```
------ pybind11_tests.cpython-312-x86_64-linux-gnu.so file size: 5252640
```

With this PR:
```
------ pybind11_tests.cpython-312-x86_64-linux-gnu.so file size: 5257248
```

Factor: 5257248 / 5252640 = 1.0008772731426483

**Comparison with stock Python and other systems for Python-C++ bindings:**

* [Python functions (built-in & native) are pickleable.](https://github.com/google/pywrapcc/pull/30099#issuecomment-1947027004)

* [SWIG functions are pickleable.](https://github.com/google/pywrapcc/pull/30099#issuecomment-1946921946)

* [PyCLIF-C-API functions are pickleable.](https://github.com/google/clif/) (Because they are implemented exactly like stock Python build-in functions.)

* [Boost.Python functions are not pickleable.](https://github.com/rwgk/stuff/blob/master/test_with_boost_python/test_pickle_simple_callable_build_and_test.txt)

* [nanobind functions are not pickleable.](https://github.com/google/pywrapcc/pull/30099#issuecomment-1946877566)

________
________
________

**Everything below are very technical details:**

Why is

```c++
m.def("simple_callable", []() { return 0; });
```

not pickleable before this PR?

The reason is that the `simple_callable` is implemented as shown by `repr(simple_callable)`:

```
<built-in method simple_callable of PyCapsule object at 0x...>
```

To Python it appears to be a bound function of the type `PyCapsule`. (The reasons for this choice of implementation are deep and omitted here.)

`pickle.dumps(simple_callable)` is capable of pickling built-in methods. It does that in two steps:

```
simple_callable.__reduce_ex__(0)
```

produces this tuple (see [`__reduce_ex__` documentation](https://docs.python.org/3/library/pickle.html#object.__reduce_ex__)):

```
(<built-in function getattr>, (<capsule object NULL at 0x...>, 'simple_callable'))
```

pickle then recurses, attempting to serialize `<built-in function getattr>` (no problem), `<capsule object NULL at 0x...>` (**problem**), and `'simple_callable'` (no problem).

The attempt to serialize `<capsule object NULL at 0x...>` fails with this exception (copy-pasted from pytest output):

```
>       pickle.dumps(m.simple_callable)
E       TypeError: cannot pickle 'PyCapsule' object
```

While this is not the desired behavior when pickling `simple_callable`, there are very good reasons in general that `PyCapsule` objects are not pickleable. See, for example, here:

* https://github.com/uqfoundation/dill/pull/477/files#diff-bdd40cc870892c410adce8c1b155daf5e6c5b5e7192e751f171e6dae6a578dc1R1220

```python
warnings.warn('Creating a new PyCapsule %s for a C data structure that may not be present in memory. Segmentation faults or other memory errors are possible.' % (name,), UnpicklingWarning)
```

The solution implemented in this PR is to

1. replace the `PyCapsule` with a custom built-in type, wrapping the [`pybind11::detail::function_record` C++ type](https://github.com/pybind/pybind11/blob/8b48ff878c168b51fe5ef7b8c728815b9e1a9857/include/pybind11/attr.h#L189-L269) the good-old way, with manually written bindings (implemented in include/pybind11/detail/function_record_pyobject.h),

5. which then makes it possible to provide a `__reduce_ex__` implementation to achieve the desired behavior.

The new `repr(simple_callable)` is:

```
<built-in method simple_callable of pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_1 object at 0x...>
```

Side note: The Python type name is versioned to ensure ABI compatibility, but to maximize compatibility it is independent of `PYBIND11_INTERNALS_VERSION`.

`simple_callable.__reduce_ex__(0)` now produces:

```
(<built-in function getattr>, (<pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_1 object at 0x...>, 'simple_callable'))
```

When pickle recurses to call `__reduce_ex__` of the wrapped `function_record` object, the result is:

```
(<built-in function eval>, ("__import__('importlib').import_module('pybind11_tests.pickling')",))
```

Very simple! — Your author has to admit though that it took quite a while to figure this out. See the development history of google/pybind11clif#30099 for the many dead ends explored before this solution was discovered.

To explain how this works in the `pickle.load()` step:

1. `eval("__import__('importlib').import_module('pybind11_tests.pickling')")` produces a reference to the imported `pybind11_tests.pickling` module.

2. `getattr(imported_module, 'simple_callable')` simply accesses what was just imported.

Note that `__import__('pybind11_tests.pickling')` only produces the top-level module (`pybind11_tests` in this case), as explained in the [`importlib.import_module()` documentation](https://docs.python.org/3/library/importlib.html#importlib.import_module).
________
________
________
This PR is a backport of google/pybind11clif#30099

## Suggested changelog entry:

```rst
pybind11-bound functions are now pickleable.
```

### CODE REVIEW

**Comment by rwgk** [comment]
@henryiii This is now ready for review.

@rainwoodman FYI

File: include/pybind11/detail/function_record_pyobject.h [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+    /* inquiry tp_is_gc */ nullptr,
+    /* PyObject *tp_bases */ nullptr,
+    /* PyObject *tp_mro */ nullptr,
+    /* PyObject *tp_cache */ nullptr,
+    /* PyObject *tp_subclasses */ nullptr,
+    /* PyObject *tp_weaklist */ nullptr,
+    /* destructor tp_del */ nullptr,
+    /* unsigned int tp_version_tag */ 0,
+    /* destructor tp_finalize */ nullptr,
+#if PY_VERSION_HEX >= 0x03080000
```
Comment (henryiii) [inline include/pybind11/detail/function_record_pyobject.h:111]: I wasn't aware we supported Python < 3.8.

**Comment by henryiii** [comment]
Yes, this immediately breaks:

```
ImportError while loading conftest '/Users/henryschreiner/git/scikit-hep/boost-histogram/tests/conftest.py'.
tests/conftest.py:16: in <module>
    import boost_histogram as bh
src/boost_histogram/__init__.py:3: in <module>
    from . import accumulators, axis, numpy, storage
src/boost_histogram/axis/__init__.py:24: in <module>
    from . import transform
src/boost_histogram/axis/transform.py:156: in <module>
    sqrt = Function("_sqrt_fn", "_sq_fn", convert=_internal_conversion, name="sqrt")
src/boost_histogram/axis/transform.py:145: in __init__
    self._this = cpp_class(forward, inverse, convert, name)
E   ValueError: PyCapsule_GetName called with invalid PyCapsule object
```

This is a core performance requirement for many applications. I'm a hard -1 unless this can be fixed.

**Comment by rwgk** [comment]
It's true that pickling functions is rare, but I stumbled over this multiple times while working at Google. Note that SWIG-wrapped and PyCLIF-wrapped functions are pickleable (those two systems are still in wide use there). If functions are pickleable, the feature is getting used, and if not, people are forced to fish for workarounds, which can be a significant time sink depending on the situation.

Global testing at Google passed with the original PR (google/pybind11clif#30099).

The boost-histogram code is using `pybind11::detail` and goes deep into pybind11 implementation details:

* https://github.com/scikit-hep/boost-histogram/blob/460ef90905d6a8a9e6dd3beddfe7b4b49b364579/include/bh_python/transform.hpp#L70-L85

Copying here for easy reference:

```C++
        if(auto cfunc = func.cpp_function()) {                                  
            auto c = py::reinterpret_borrow<py::capsule>(                       
                PyCFunction_GET_SELF(cfunc.ptr()));                             
                                                                                
            auto rec = c.get_pointer<py::detail::function_record>();            
                                                                                
            if(rec && rec->is_stateless                                         
               && py::detail::same_type(                                        
                   typeid(raw_t*),                                              
                   *reinterpret_cast<const std::type_info*>(rec->data[1]))) {   
                struct capture {                                                
                    raw_t* f;                                                   
                };                                                              
                return std::make_tuple((reinterpret_cast<capture*>(&rec->data))->f,
                                       src);                                    
            }                                                                   
                                                                                
            // Note that each error is slightly different just to help with debugging
            throw py::type_error("Only ctypes double(double) and C++ functions allowed "
                                 "(must be stateless)");                        
        }                                                                       
```

We'd need to provide a public API for that performance optimization.

We could provide something like `PYBIND11_HAS_PUBLIC_FUNCTION_RECORD_API` to support backward compatibility. Would that be acceptable?

File: include/pybind11/detail/function_record_pyobject.h (hunk 1 above)
Comment (rwgk) [reply include/pybind11/detail/function_record_pyobject.h]: Thanks for catching that, removed with commit e8e921da026accb33eb350198c89f5616940fae5.

**Comment by rwgk** [comment]
@henryiii It looks like boost-histogram copy-paste-tweaked this pybind11 code:

* https://github.com/pybind/pybind11/blob/f365314ec0a86c76d697b9fa4d7a3e804ff35180/include/pybind11/functional.h#L84-L126

Did you consider using that caster instead? (Call `load()`, then access the `value`.)

**Comment by henryiii** [comment]
Today you can use pybind11 to create a function you can call in SciPy. After this PR, that will no longer work. I had to dig into the internals a bit to make something that _takes_ a `PyCapsule` (similar to SciPy), but most users will want to provide a PyCapsule, not ingest one. A boost-histogram user is supposed to make their own function and provide it, such as with numba or pybind11; after this PR, pybind11 won't be able to produce a usable function.

`PyCapsule` is a built-in integrated API for CPython to access a callable and bypass the Python layer. I don't think we should throw away a standard lightly.

**Comment by rwgk** [comment]
> Today you can use pybind11 to create a function you can call in SciPy. After this PR, that will no longer work.

I'm really surprised, could you please provide an example? — The Google global testing ~7 months ago had a lot of scipy dependencies for sure, although I don't know with what version of scipy.

**Comment by henryiii** [comment]
I'm confused by the way PyCapsule is used here. `a.b` says that `b` is a method of a PyCapsule, not a PyCapsule itself. SciPy's `_ccallback_c.check_capsule` returns False for a pybind11 function. If you wrap it in an explicit `py::capsule` conversion, it works (including after this PR).

If boost-histogram is the only major issue, I can fix that.

Here's the sample code, including the raw pointer method that ChatGPT suggested too:

<details>
<summary>somecode.cpp:</summary>

```cpp
// cppimport
#include <pybind11/pybind11.h>

namespace py = pybind11;

double square(double x) {
    return x * x;
}

void* get_my_function() {
    return reinterpret_cast<void*>(square);
}


py::capsule get_my_capsule() {
    return py::capsule(reinterpret_cast<void*>(square), "double (double)");
}


PYBIND11_MODULE(somecode, m) {
    m.def("square", &square);
    m.def("square_callable", &get_my_function);
    m.def("square_capsule", &get_my_capsule);
}

/*
<%
setup_pybind11(cfg)
%>
*/
```

</details>

<details>
<summary>example.py:</summary>

```cpp
import contextlib
import time

import cppimport.import_hook

import somecode

import scipy
import scipy.integrate


@contextlib.contextmanager
def timing(description: str) -> None:
    start = time.monotonic()
    yield
    ellapsed_time = time.monotonic() - start

    print(f"{description}: {ellapsed_time*1_000_000:.1f}µs")

with timing("Through Python"):
    integral = scipy.integrate.quad(somecode.square, 0, 1)
print(integral)

llc = scipy.LowLevelCallable(somecode.square_callable(), signature="double (double)")
with timing("With LowLevelCallable"):
    integral = scipy.integrate.quad(llc, 0, 1)
print(integral)

llc2 = scipy.LowLevelCallable(somecode.square_capsule())
with timing("With PyCapsule"):
    integral = scipy.integrate.quad(llc2, 0, 1)
print(integral)
```

</details>

```console
$ uv init
$ uv add pybind11 scipy cppimport
$ uv run python example.py
Through Python: 43.3µs
(0.33333333333333337, 3.700743415417189e-15)
With LowLevelCallable: 12.1µs
(0.33333333333333337, 3.700743415417189e-15)
With PyCapsule: 7.0µs
(0.33333333333333337, 3.700743415417189e-15)
```

Is there a way to pass this through without the explicit `py::capsule` wrapping? If not, then it's quite a bit safer than I originally thought.

**Comment by rwgk** [comment]
Thanks! That looks promising at first glance. I'll look at this carefully tomorrow.

**Comment by henryiii** [comment]
>  (Call `load()`, then access the `.value`.)

I get "`.value` is a protected member", by the way.

**Comment by rwgk** [comment]
> > (Call `load()`, then access the `.value`.)
> 
> I get "`.value` is a protected member", by the way.

I want to add a pybind11 unit test that mirrors your situation.

Is your work accessible publicly, for me to use us a starting point?

**Comment by henryiii** [comment]
https://github.com/scikit-hep/boost-histogram/blob/460ef90905d6a8a9e6dd3beddfe7b4b49b364579/include/bh_python/transform.hpp is available, I don't have the various experiments I've been trying locally anywhere, though, since none of them worked. https://boost-histogram.readthedocs.io/en/latest/user-guide/transforms.html is where I describe how to use this (though I don't mention making a function in pybind11, I was assuming numba would be the most common way).

**Comment by rwgk** [comment]
> Support for LowLevelCallable was added in #902, in 2017.

Interesting, this escaped me completely before.

@henryiii Please take a look here (demo PR #5585):

https://github.com/pybind/pybind11/commit/8b500da6a3b568d557f8cfb378477d48bad9e136 — Add `.get_capsule_for_scipy_LowLevelCallable()` method in function_record_pyobject.h

This is to show that the new dedicated function record Python type introduced with this PR gives us new leverage.

I don't a have good idea for making the magic `.get_capsule_for_scipy_LowLevelCallable()` method type safe though.

File: tests/test_pickling.py [hunk 2]
```diff
@@ -9,18 +9,41 @@
 from pybind11_tests import pickling as m
 
 
-def test_pickle_simple_callable():
+def test_assumptions():
+    assert pickle.HIGHEST_PROTOCOL >= 0
```
Comment (henryiii) [inline tests/test_pickling.py:13]: Why this? This isn't a test for pybind11, it's a test of the Python standard library? https://docs.python.org/3/library/pickle.html#pickle.HIGHEST_PROTOCOL and it's at least 4 since Python 3.4.

File: tests/test_pickling.py [hunk 3]
```diff
@@ -9,18 +9,41 @@
...
+
+
+@pytest.mark.parametrize("protocol", range(pickle.HIGHEST_PROTOCOL + 1))
```
Comment (henryiii) [inline tests/test_pickling.py:16]: Interesting, we don't normally support protocol 0 with `py::pickle`, but I guess this does?

**Review by henryiii — APPROVED** [review]

File: tests/test_pickling.py (hunk 3 above)
Comment (rwgk) [reply tests/test_pickling.py:16]: I changed it like this:

```diff
-def test_assumptions():
+def all_pickle_protocols():
     assert pickle.HIGHEST_PROTOCOL >= 0
+    return range(pickle.HIGHEST_PROTOCOL + 1)
 
 
-@pytest.mark.parametrize("protocol", range(pickle.HIGHEST_PROTOCOL + 1))
+@pytest.mark.parametrize("protocol", all_pickle_protocols())
 def test_pickle_simple_callable(protocol):
```

Basically, I'm paranoid about accidentally not running `test_pickle_simple_callable()` at all.

This is easily overlooked:
```
test_pickling.py::test_pickle_simple_callable[protocol0] SKIPPED (got empty parameter set ['protocol'], function test_pickle_simple_...)
```

Comment (rwgk) [reply tests/test_pickling.py:16]: Oof, sorry, the above was meant to be a response to the other question.

> Interesting, we don't normally support protocol 0 with `py::pickle`, but I guess this does?

Yes, this is completely independent. There is no reason to limit what protocol versions are accepted.

**Comment by rwgk** [comment]
I'm super confused ...

commit 61c9c6d350db3be54f4a2da38ab278a4aa7f54ec shows up in the list of commits here (https://github.com/pybind/pybind11/pull/5580), before the "rwgk merged" point, but it's missing on master:

* https://github.com/pybind/pybind11/blob/e7e5d6e5bb0af543a2ded6d34163176c3e6ab745/tests/test_pickling.py

How can that be?

**Comment by henryiii** [comment]
I highly, highly, highly recommend rebasing and never making merge commits. Merge commits are evil and can cause strange results. There's even a "rebase" button in the UI. Though it's possible this is a GitHub bug, it probably wouldn't happen on linear history.

File: tests/test_pickling.py (hunk 3 above)
Comment (henryiii) [reply tests/test_pickling.py:16]: If pickle reports a maximum pickle version of 0, pickle would be broken. That would be a Python bug, I don't think we should be worried about Python bugs of that magnitude. Especially since it only would produce a minor warning in the test suite.

**Comment by henryiii** [comment]
You can cherry pick the commit, though I'd rather just use the value without testing it. We should rely on Python being correctly implemented, it adds distractions to our test suite.

**Comment by henryiii** [comment]
I'm getting a warning on every single file when compiling now:

```
In file included from /Users/henryschreiner/git/software/pybind11/include/pybind11/pybind11.h:15:
/Users/henryschreiner/git/software/pybind11/include/pybind11/detail/function_record_pyobject.h:43:26: warning: cast from 'PyObject *(*)(PyObject *, PyObject *, PyObject *)' (aka '_object *(*)(_object *, _object *, _object *)') to 'PyCFunction' (aka '_object *(*)(_object *, _object *)') converts to incompatible function type [-Wcast-function-type-mismatch]
   43 |     = {{"__reduce_ex__", (PyCFunction) reduce_ex_impl, METH_VARARGS | METH_KEYWORDS, nullptr},
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by rwgk** [comment]
> I'm getting a warning on every single file when compiling now:
> 
> ```
> In file included from /Users/henryschreiner/git/software/pybind11/include/pybind11/pybind11.h:15:
> /Users/henryschreiner/git/software/pybind11/include/pybind11/detail/function_record_pyobject.h:43:26: warning: cast from 'PyObject *(*)(PyObject *, PyObject *, PyObject *)' (aka '_object *(*)(_object *, _object *, _object *)') to 'PyCFunction' (aka '_object *(*)(_object *, _object *)') converts to incompatible function type [-Wcast-function-type-mismatch]
>    43 |     = {{"__reduce_ex__", (PyCFunction) reduce_ex_impl, METH_VARARGS | METH_KEYWORDS, nullptr},
>       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 warning generated.
> ```

Sorry I didn't see this before. Is this still an issue? What are the exact conditions to reproduce?

We have these warning suppressions already:

```C++
PYBIND11_WARNING_PUSH
#if defined(__GNUC__) && __GNUC__ >= 8
PYBIND11_WARNING_DISABLE_GCC("-Wcast-function-type")
#endif
#if defined(__clang__) && !defined(__apple_build_version__) && __clang_major__ >= 19
PYBIND11_WARNING_DISABLE_CLANG("-Wcast-function-type-mismatch")
#endif
static PyMethodDef tp_methods_impl[]
    = {{"__reduce_ex__", (PyCFunction) reduce_ex_impl, METH_VARARGS | METH_KEYWORDS, nullptr},
       {nullptr, nullptr, 0, nullptr}};
PYBIND11_WARNING_POP
```

Do we need to work on the preprocessor conditions? — I didn't want to make them too general, maybe that's backfiring now?

I remember I looked around quite a bit for the best way to implement that line, when I was working on the code originally, but I couldn't find a cleaner solution.

Coincidentally, a couple days ago I spent some time looking at issue #5600, specifically: https://github.com/pybind/pybind11/issues/5600#issuecomment-2781306153

For that situation ChatGPT suggested among other things:

> ✅ Try `METH_FASTCALL | METH_KEYWORDS` and adjust the dispatcher signature to take `PyObject **args, Py_ssize_t nargsf, PyObject *kwargs`. This matches 3.12’s preferred calling convention.

Maybe that could help here, too? In the long run. Warning suppressions seem best as an immediate solution.

**Comment by henryiii** [comment]
I’m on macOS. So probably the clang but not Apple is the problem.

**Comment by rwgk** [comment]
> I’m on macOS. So probably the clang but not Apple is the problem.

Does this silence the warnings for you?

```
-#if defined(__clang__) && !defined(__apple_build_version__) && __clang_major__ >= 19
+#if defined(__clang__)
```

It's a bit sweeping, but I think it should be fine? It's just for that one cast. Please let me know, it's a quick PR.

**Comment by henryiii** [comment]
I’ll try to check tomorrow, only have my phone ATM.

**Comment by rwgk** [comment]
> I’ll try to check tomorrow, only have my phone ATM.

I think I have something better for you: PR #5608 (CI was still running when I posted this, but it's looking promising.)
