### PR TITLE
Set __hash__ to None for types that defines __eq__ but not __hash__

### LINKED ISSUE #2191: Overriding __eq__ does not set __hash__ to None
## Issue description

The Python documentation [states](https://docs.python.org/3/reference/datamodel.html#object.__hash__)

> A class that overrides `__eq__()` and does not define `__hash__()` will have its `__hash__()` implicitly set to None. When the `__hash__()` method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking `isinstance(obj, collections.abc.Hashable)`.

Thus if we override `__eq__` but not `__hash__` we should get an unhashable type (e.g. cannot be used in a `set` container). Pybind however seems to always have a `__hash__` implemented, regardless if we override `__eq__`. The expected behaviour is that `__hash__` is set to `None`

## Reproducible example code
In Python it exhibits the following behaviour

```python
from collections import abc

class MyClass1:
    pass

class MyClass2:
    def __eq__(self, other):
        return True

def main():
    c1 = MyClass1()
    c2 = MyClass2()
    print(isinstance(c1, abc.Hashable)) # True 
    print(isinstance(c2, abc.Hashable)) # False <- OK

if __name__ == "__main__":
    main()
```

Using pybind
```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;

class DummyClass {};
class DummyClass2 {};

PYBIND11_MODULE(DummyClass, m) {
    py::class_<DummyClass>(m, "MyClass1")
            .def(py::init());
    py::class_<DummyClass2>(m, "MyClass2")
            .def(py::init())
            .def("__eq__", [](py::object&) { return true; });
}
```
```python
from collections import abc
from lib.DummyClass import MyClass1, MyClass2

def main():
    c1 = MyClass1()
    c2 = MyClass2()
    print(isinstance(c1, abc.Hashable)) # True 
    print(isinstance(c2, abc.Hashable)) # True <- NOT OK

if __name__ == "__main__":
    main()
```

# The workaround
A workaround is to manually add `.attr("__hash__") = py::none()`

I'm assuming it should be possible to detect if there is a `__eq__` override without any `__hash__` override and then set the attribute. This would resolve the deviating/unexpected behaviour.

### PR DESCRIPTION
**Pull request by sizmailov**
PR patches `py::class_<>::def` as discussed in  https://github.com/pybind/pybind11/pull/2287

fixes #2191

### CODE REVIEW

File: include/pybind11/pybind11.h [hunk 1]
```diff
@@ -1144,7 +1151,7 @@ class class_ : public detail::generic_type {
     class_ &def(const char *name_, Func&& f, const Extra&... extra) {
         cpp_function cf(method_adaptor<type>(std::forward<Func>(f)), name(name_), is_method(*this),
                         sibling(getattr(*this, name_, none())), extra...);
-        attr(cf.name()) = cf;
```
Comment (sizmailov) [inline include/pybind11/pybind11.h:1147]: Does anyone know why this line was not `attr(name_) = cf;` ? Just curious.

Comment (bstaletic) [reply include/pybind11/pybind11.h:1147]: It used to be `attr(name_) = cpp_function( ... )` until [this commit](https://github.com/pybind/pybind11/commit/570822102c037600781da816d1a083db031c8cde#diff-6645501a414a69e6b16abfe4bee9025fR676).

Comment (sizmailov) [reply include/pybind11/pybind11.h:1147]: Indeed, it's intended change. Had to do `blame` myself. Thanks!

File: include/pybind11/pybind11.h [hunk 2]
```diff
@@ -1047,6 +1047,13 @@ inline void call_operator_delete(void *p, size_t s, size_t a) {
     #endif
 }
 
+inline void add_class_method(object& cls, const char *name_, const cpp_function &cf) {
```
Comment (YannickJadoul) [inline include/pybind11/pybind11.h:1050]: Just curious: If this PR does reduce the binary size, this `inline` is just ignored by the compiler and is only necessary to avoid the ODR?

Comment (sizmailov) [reply include/pybind11/pybind11.h:1050]: Correct.

**Comment by YannickJadoul** [comment]
Oh, what about docs, cfr. #2287? Do we need to mention this now or is it just "fixed". Or are we merging that as reworked #2278?

**Comment by bstaletic** [comment]
> Oh, what about docs, cfr. #2287? Do we need to mention this now or is it just "fixed". Or are we merging that as reworked #2278?

Unless I'm missing something, we can just treat #2191 as resolved and leave the docs alone.

**Comment by YannickJadoul** [comment]
> Unless I'm missing something, we can just treat #2191 as resolved and leave the docs alone.

Fine with me. I just saw @jbarlow83's remark (https://github.com/pybind/pybind11/pull/2287#discussion_r453143724).
@ixje, you brought up this issue in the first place; do you think further docs are needed, or is just being consistent with Python good enough?

File: tests/test_operator_overloading.cpp [hunk 3]
```diff
@@ -187,6 +187,38 @@ TEST_SUBMODULE(operators, m) {
...
+    // test_overriding_eq_reset_hash
+    // #2191 Overriding __eq__ should set __hash__ to None
+    struct Comparable {
+        int value;
+        bool operator==(const Comparable& rhs) const {return value == rhs.value;}
+    };
+
+    struct Hashable : Comparable {
+        explicit Hashable(int value): Comparable{value}{};
+        size_t hash() const { return value % 32; /* full of collisions */ }
```
Comment (rwgk) [inline tests/test_operator_overloading.cpp:201]: Is "full of collisions" important to the test? The test only uses one value (15).

File: tests/test_operator_overloading.py [hunk 4]
```diff
@@ -126,3 +126,18 @@ def test_nested():
...
+    assert m.Comparable(15) == m.Comparable(15)
+
+    with pytest.raises(TypeError):
+        hash(m.Comparable(15))  # TypeError: unhashable type: 'm.Comparable'
+
+    for hashable in (m.Hashable, m.Hashable2):
+        assert hashable(15) is not hashable(15)
+        assert hashable(15) == hashable(15)
+
+        assert hash(hashable(15)) == hash(hashable(15))
```
Comment (rwgk) [inline tests/test_operator_overloading.py:143]: Is this to prove that the correct hash implementation is used?
Does `hash(hashable(15)) == hash(hashable(15 + 32))` make sense?
To prove that the `% 32` is actually used.

Comment (YannickJadoul) [reply tests/test_operator_overloading.py:143]: If the default `id`-based comparison would be used, this assertion would fail (I believe? Unless the memory location of the temporary `hashable(15)` gets recycled?

Comment (rwgk) [reply tests/test_operator_overloading.py:143]: Yeah, I agree, but it is so cheap to be more certain, I'd definitely seize the opportunity.

**Comment by ixje** [comment]
> @ixje, you brought up this issue in the first place; do you think further docs are needed, or is just being consistent with Python good enough?

I did the docs PR when we still had the believe that the impact of actually solving it was too high. I'll close that one in favour of this, as it is no longer required. Thanks everybody for resolving this ❤️

File: tests/test_operator_overloading.cpp (hunk 3 above)
Comment (sizmailov) [reply tests/test_operator_overloading.cpp:201]: Not really. Can be reduced to `return value`. I'll update PR.

File: tests/test_operator_overloading.py (hunk 4 above)
Comment (sizmailov) [reply tests/test_operator_overloading.py:143]: The `__hash__` contract implies that equal object has same hash. This is what is checked  here (along with hashibility of the objects). 

>  Does hash(hashable(15)) == hash(hashable(15 + 32)) make sense?

Only as verification of concrete implementation. The exact hash values are implementation detail. 

@YannickJadoul, you are correct, default hash would fail here.

Comment (YannickJadoul) [reply tests/test_operator_overloading.py:143]: > @YannickJadoul, you are correct, default hash would fail here.

Did you try this? Because I could imagine Python creating a `hashable(15)` at memory location `x`, computing the `hash`, deallocating the `hashable` object as it goes to refcount 0, the creating `hashable(15)` at the same memory location, and computing the same `id`-based hash?

Comment (sizmailov) [reply tests/test_operator_overloading.py:143]: Yes, I've tried to mock it with 
```python
        assert hashable(15) is not hashable(15)
        assert hashable(15) == hashable(15)
        del hashable.__hash__
        assert hash(hashable(15)) == hash(hashable(15))
```
and it fails with 

```
>           assert hash(hashable(15)) == hash(hashable(15))
E           AssertionError: assert -9223363257492360940 == 8779362415047
E            +  where -9223363257492360940 = hash(<pybind11_tests.operators.Hashable object at 0x7fc1ac731148>)
E            +    where <pybind11_tests.operators.Hashable object at 0x7fc1ac731148> = <class 'pybind11_tests.operators.Hashable'>(15)
E            +  and   8779362415047 = hash(<pybind11_tests.operators.Hashable object at 0x7fc1ac731c70>)
E            +    where <pybind11_tests.operators.Hashable object at 0x7fc1ac731c70> = <class 'pybind11_tests.operators.Hashable'>(15)
```

Comment (YannickJadoul) [reply tests/test_operator_overloading.py:143]: I actually just tried that. I knew I'd seen this Python trap before:

```pycon
>>> class X: pass
... 
>>> id(X()), id(X())
(140256801227776, 140256801227776)
>>> hash(X()) == hash(X())
True
>>> x = X()
>>> y = X()
>>> id(x), id(y)
(140256801227776, 140256801227832)
>>> hash(x) == hash(y)
False
```

The same holds for running as a script:

```python
class X: pass

print(id(X()), id(X()))
print(hash(X()) == hash(X()))

x, y = X(), X()

print(id(x), id(y))
print(hash(x) == hash(y))
```

```
$ python3 test.py 
140000331939064 140000331939064
True
140000331939064 140000331959096
False
```

Comment (sizmailov) [reply tests/test_operator_overloading.py:143]: Hm. I don't mind to test against actual values of `hash(hashable(...))` to verify that we use the definition we want.

Comment (sizmailov) [reply tests/test_operator_overloading.py:144]: I've added `assert hash(hashable(15)) == 15` so we know for sure the default `id`-based implementation is not involved.

Comment (YannickJadoul) [reply tests/test_operator_overloading.py:144]: OK, that's also fine. I was just thinking to not have them as temporary objects, but this does the same, I suppose.

Comment (YannickJadoul) [reply tests/test_operator_overloading.py:144]: > Yes, I've tried to mock it with
> 
> ```python
>         assert hashable(15) is not hashable(15)
>         assert hashable(15) == hashable(15)
>         del hashable.__hash__
>         print(hashable.__hash__)
>         assert hash(hashable(15)) == hash(hashable(15))
> ```
> 
> and it fails with
> 
> ```
> <slot wrapper '__hash__' of 'object' objects>
> 
> ...
> 
> >           assert hash(hashable(15)) == hash(hashable(15))
> E           AssertionError: assert -9223363257492360940 == 8779362415047
> E            +  where -9223363257492360940 = hash(<pybind11_tests.operators.Hashable object at 0x7fc1ac731148>)
> E            +    where <pybind11_tests.operators.Hashable object at 0x7fc1ac731148> = <class 'pybind11_tests.operators.Hashable'>(15)
> E            +  and   8779362415047 = hash(<pybind11_tests.operators.Hashable object at 0x7fc1ac731c70>)
> E            +    where <pybind11_tests.operators.Hashable object at 0x7fc1ac731c70> = <class 'pybind11_tests.operators.Hashable'>(15)
> ```

Ah, wait. Hadn't seen that. Interesting, so here it doesn't do that? Maybe because of the AST rewrite pytest does?

Comment (sizmailov) [reply tests/test_operator_overloading.py:144]: Whatever it is I don't think it's a reliable behavior, i.e. it might change from version to version from one day of week to another. I think now we are backed with better test case.

Comment (YannickJadoul) [reply tests/test_operator_overloading.py:144]: Agreed! :-)

**Comment by YannickJadoul** [comment]
I think this was approved by everyone? I'm merging.

Thank you very much, once again, @sizmailov! :-)
