### PR TITLE
Qualify some references to `module`

### LINKED ISSUE #2488: [BUG] Compilation error on latest Visual Studio 19 because of module keyword
## Issue description
Related to https://github.com/pybind/pybind11/pull/1639 that wasn't merged.

Compilation fails because of the `module` keyword. In VS, modules are now activated when using `/std:c++latest`. 

```
1>...\include\pybind11/pybind11.h(837,5): error C2059: syntax error: 'module'
1>...\include\pybind11/pybind11.h(837,71): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>...\include\pybind11/pybind11.h(837,5): error C7586: a 'module' directive must end with a ';' on the same line
```

This compilation error currently happens only with the preview version of Visual Studio (VS 19 16.8.0 Preview 3.0).

[This blog post](https://devblogs.microsoft.com/cppblog/standard-c20-modules-support-with-msvc-in-visual-studio-2019-version-16-8/) talks about the recent update in Visual Studio.

VS compiler consider module as a keyword [only is it's at the beginning of the line](https://docs.microsoft.com/en-us/cpp/cpp/import-export-module?view=vs-2019#remarks). 
However, in the module class in pybind.h, there is one line with module at the beginning of the line:
```
module def_submodule(const char *name, const char *doc = nullptr)
{ ... }
```
My dirty fix to make it compile is just to add [[nodiscard]] to this function:
```
[[nodiscard]] module def_submodule(const char *name, const char *doc = nullptr)
```
Maybe a safer fix is to rename the class.

## Reproducible example code
Just including pybind11.h fails.
```
#include <pybind11/pybind11.h>
int main() { return 0; }
```

### PR DESCRIPTION
**Pull request by bstaletic**
Sometimes, latest MSVC gets confused about whether `module` should be
treated as a keyword or as an identifier name. In those cases, we need
to qualify `module` as `pybind11::module`.

Concerns left to address:

- Do other places need to be qualified?
- How do we test this?

Fixes #2488 

There are 10 places where `module` is the first token on the line. For reference, read #2488.

### CODE REVIEW

**Comment by Predelnik** [comment]
Waiting for confirmation but most likely this error is given according to the standard. Clang allows such usage inside namespace but it probably is too lenient, gcc with modules patch [also produces an error](https://gcc.godbolt.org/z/nGnvcK). So there's a chance it will be naturally tested sometime in the future by any compiler with C++20 enabled.

**Comment by bstaletic** [comment]
That's definitely a possibility. Maybe we should preemptively qualify all mentions of `module` type.

This might be a good idea for a clang-tidy check.

**Comment by YannickJadoul** [comment]
Alternative solution, already proposed to @bstaletic on Gitter: what about adding a `using module_ = pybind11::module` somewhere (or even rename `module` to `module_` and have the typdef the other way around)? The underscore is also how pybind11 deals with `int`, `class`, etc.

**Comment by bstaletic** [comment]
I'm fine with anything that doesn't break existing users. Just a note though.

> (or even rename `module` to `module_` and have the typdef the other way around)

That breaks ABI of `py::module`, but I'm not concerned about that, in this case.

**Comment by YannickJadoul** [comment]
I'd prefer `module_` (whichever way you choose to be the "real" class vs. the alias) over arbitrarily having to fully qualify the `module` type but nothing else in pybind11, I believe.

**Comment by bstaletic** [comment]
Alright, I'll wait for a while, to hear any other possible opinions before proceeding.

**Comment by henryiii** [comment]
I was going to disagree but I think I agree now. As long as users continue to use `py::module`, which is still valid, I think it's fine.

File: include/pybind11/pybind11.h [hunk 1]
```diff
@@ -900,30 +900,30 @@ class module : public object {
             py::module m2 = m.def_submodule("sub", "A submodule of 'example'");
             py::module m3 = m2.def_submodule("subsub", "A submodule of 'example.sub'");
     \endrst */
-    module def_submodule(const char *name, const char *doc = nullptr) {
+    module_ def_submodule(const char *name, const char *doc = nullptr) {
```
Comment (bstaletic) [inline include/pybind11/pybind11.h:903]: This is the one that created the error. It is also a member function of `py::module`. This meant that going with `using module_ = module;` doesn't help and I had to rename the whole class.

Unless we were to go with `pybind11::module`, but @YannickJadoul seems to be against that.

**Review by bstaletic — COMMENTED** [review]
Where and how should this change be documented? Do we want to recommend `module_` from now on?

File: docs/reference.rst [hunk 2]
```diff
@@ -46,7 +46,7 @@ With reference counting
 Convenience classes for specific Python types
 =============================================
 
-.. doxygenclass:: module
+.. doxygenclass:: module_
```
Comment (bstaletic) [inline docs/reference.rst:49]: Did the change to `py::module_` break anything else in the docs?

File: include/pybind11/pybind11.h (hunk 1 above)
Comment (henryiii) [reply include/pybind11/pybind11.h:903]: I think we should recommend `py::module`; this is just an internal change since `module` unqualified is not allowed in some cases. Users should not be exporting the pybind11 namespace. I don't think users should even know that a `module_` exists normally.

Comment (henryiii) [reply include/pybind11/pybind11.h:903]: > whichever way you choose to be the "real" class vs. the alias

He was fine with either way, just suggesting using `module_` internally instead of writing `pybind11::module` vs. unqualified names everywhere (internally only).

Comment (bstaletic) [reply include/pybind11/pybind11.h:903]: Okay, I added a note in the changelog.

**Review by henryiii — APPROVED** [review]

File: include/pybind11/pybind11.h (hunk 1 above)
Comment (YannickJadoul) [reply include/pybind11/pybind11.h:903]: > but @YannickJadoul seems to be against that.

I'm not against it, for the record. I probably prefer the other one, since it's more consistent with the rest of pybind11 :-)

> I think we should recommend py::module; this is just an internal change since module unqualified is not allowed in some cases.

Also true. So normally, users shouldn't even notice, and if they do have a `using pybind11::module;` or `using namespace pybind11;`, we can't really be blamed?
But explaining to use `module_` seems a lot easier than explaining when to use `py::module`? And it's more consistent with `class_` and `enum_` and `int_` and `float_`?

Comment (henryiii) [reply include/pybind11/pybind11.h:903]: `class`, `enum`, `int`, and `float` have been C++ keywords since the dawn of time (more or less). `module` is _slighly_ special in C++20, and is not a true keyword. And the restrictions on using it are the same for pybind11 as with any other code; including user code. Someone might already write `auto module = ...; module...`, and we can't fix/help that. I don't think we should try to force pretty much every pybind11 project to change the name of `py::module` unless we really had to (and `module` is easier to remember than `module_`). And I think 99% of pybind11 follows the examples and uses `py` as the namespace.

If C++ were to make this a true keyword in 3*n years (I doubt it), then we could force a transition. But I really doubt it, it's too common a term.

Comment (YannickJadoul) [reply include/pybind11/pybind11.h:903]: No, I think I agree: no need to force anything. Just wondering if we should give the "safe" example and just start using `py::module_` in examples, etc; more from a perspective of nudging users than to tell them to transition.

If we don't want to do that, I'm also fine with `pybind11::module` in our code, btw. Thinking about it again, I don't really object to that approach either. Up to @bstaletic who took up the task of fixing this :-)

Comment (bstaletic) [reply include/pybind11/pybind11.h:903]: From what I can tell, no one has a particularly strong opinion. The current patch should work, so why not go with it, as is and, if people start having troubles in their code, we can change the docs to use `module_` more consistently?

Any objections to that idea?

To be honest, I'm just try not to end up endlessly bikeshedding mostly equivalent alternatives.

**Review by YannickJadoul — APPROVED** [review]

**Comment by YannickJadoul** [comment]
Not to stall this PR, but this might be worth mentioning to @wjakob; it's a topic with a potential for strong feelings.

**Comment by wjakob** [comment]
This change doesn't bother me at all. ABI compatibility should be fine as well -- the PR doesn't affect the memory layout of data structures that are shared between plugins, so this is all fine.

**Review by wjakob — APPROVED** [review]
