### PR TITLE
Fix & test for issue #4288 (unicode surrogate character in Python exception message).

### LINKED ISSUE #4288: Bug: exception in noexcept `what()` when Python exception contains a surrogate character
### Discussed in https://github.com/pybind/pybind11/discussions/4287

<div type='discussions-op-text'>

<sup>Originally posted by **TheShiftedBit** October 26, 2022</sup>
By default, Python produces errors when converting encoding `str`s with utf-8 if the `str` contains surrogate characters. This can be disabled by passing `surrogatepass` as a second argument to `.encode()`. Pybind11 has this same behavior with its `str` -> `std::string` conversion. However, the bug is this: if an exception message contains a surrogate character, calling `.what()` on an `error_already_set` with such an exception causes another exception to be thrown, but since `.what()` is `noexcept`, that exception cannot be caught and the program `std::terminate`s.

I'm not sure what the correct behavior regarding surrogate characters is. Perhaps pybind11 should always use `surrogatepass`, perhaps not. However, even if that's not the right choice, it should probably use it during exception handling, or Python exceptions like this are extremely difficult to diagnose.</div>

### PR DESCRIPTION
**Pull request by rwgk**
## Description
Closes #4288. See there for background.

While at it:

* Also adding `test_error_already_set_message_with_malformed_utf8()` (passes without changes).
* Removing a stray block of code (oversight in #1895).

## Suggested changelog entry:

```rst
Bug fix: Unicode surrogate character in Python exception message leads to process termination in `error_already_set::what()`.
```

### CODE REVIEW

**Comment by henryiii** [comment]
PyPy 3.7 Windows gave:

```
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  Checking File Globs
  cross_module_gil_utils.vcxproj -> D:\a\pybind11\pybind11\build2\tests\cross_module_gil_utils.pypy37-pp73-win_amd64.pyd
  cross_module_interleaved_error_already_set.vcxproj -> D:\a\pybind11\pybind11\build2\tests\cross_module_interleaved_error_already_set.pypy37-pp73-win_amd64.pyd
  pybind11_cross_module_tests.vcxproj -> D:\a\pybind11\pybind11\build2\tests\pybind11_cross_module_tests.pypy37-pp73-win_amd64.pyd
  pybind11_tests.vcxproj -> D:\a\pybind11\pybind11\build2\tests\pybind11_tests.pypy37-pp73-win_amd64.pyd
  ------ pybind11_tests.pypy37-pp73-win_amd64.pyd file size: 23571968 (no change)
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'D:\a\pybind11\pybind11\build2\CMakeFiles\c74e89d6f5f1ea108a7628c93f4b5083\pytest.rule;D:\a\pybind11\pybind11\tests\CMakeLists.txt' exited with code -1073741819. [D:\a\pybind11\pybind11\build2\tests\pytest.vcxproj]
```

That's the expected flake, or something else? either way, I can rerun. You can access old runs at the top, there's a selectable run number there.

File: tests/test_exceptions.cpp [hunk 1]
```diff
@@ -105,11 +105,6 @@ struct PythonAlreadySetInDestructor {
     py::str s;
 };
 
-std::string error_already_set_what(const py::object &exc_type, const py::object &exc_value) {
-    PyErr_SetObject(exc_type.ptr(), exc_value.ptr());
-    return py::error_already_set().what();
-}
```
Comment (henryiii) [inline tests/test_exceptions.cpp:111]: Was this just not being used?

Comment (henryiii) [reply tests/test_exceptions.cpp:111]: Ahh, "Removing a stray block of code", got it.

Comment (rwgk) [reply tests/test_exceptions.cpp:111]: Yeah, I just forgot to remove that block after moving the code into a lambda function.

**Comment by rwgk** [comment]
> PyPy 3.7 Windows gave:
> That's the expected flake, or something else?

Something else. I've seen it for the first time 2-3 months ago. I don't know what's behind it, at all. But clearly not related to this PR.

File: include/pybind11/pytypes.h [hunk 2]
```diff
@@ -501,11 +501,28 @@ struct error_fetch_and_normalize {
         std::string message_error_string;
         if (m_value) {
             auto value_str = reinterpret_steal<object>(PyObject_Str(m_value.ptr()));
+            const char *message_unavailable_exc = "<MESSAGE UNAVAILABLE DUE TO ANOTHER EXCEPTION>";
```
Comment (Skylion007) [inline include/pybind11/pytypes.h:504]:
```suggestion
            constexpr const char *message_unavailable_exc = "<MESSAGE UNAVAILABLE DUE TO ANOTHER EXCEPTION>";
```

**Review by Skylion007 — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]
